### ISSUE TITLE
 java.lang.NullPointerException

### ISSUE THREAD

**Issue by 626838956** [Blankj/AndroidUtilCode#1017]
java.lang.NullPointerException: Argument 'grantResults' of type int[] (#2 out of 3, zero-based) is marked by @android.support.annotation.NonNull but got null for it
  	at com.blankj.utilcode.util.PermissionUtils$PermissionActivity.onRequestPermissionsResult(Unknown Source:19)
  	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7628)
  	at android.app.Activity.dispatchActivityResult(Activity.java:7478)
  	at android.app.ActivityThread.deliverResults(ActivityThread.java:4462)

**Comment by 626838956** [comment]
这个非空注解能不能去掉，代码中判断非空

**Comment by Blankj** [comment]
好的，下版本就会修复的

**Comment by Blankj** [comment]
试试 1.25.10-alpha1

**Comment by 626838956** [comment]
谢谢
