### ISSUE TITLE
1.25.9版本在自定义View里使用，布局不能预览。

### ISSUE THREAD

**Issue by xietengyue** [Blankj/AndroidUtilCode#1033]
## Describe the bug

自定义一个viewA，初始化里使用ConvertUtils.dp2px方法，在xml使用viewA时布局不能预览，查看布局右上角的信息得知报空指针。（改回1.23.7版本无报错，可预览）

- The version of utilcode: 1.25.9
- The device: 
- The version of device: 

## The code of bug

public QConstraintLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
        TypedArray typedArray = context.obtainStyledAttributes(attrs, R.styleable.QConstraintLayout);
        mLeftTextMarginLeft = typedArray.getDimension(R.styleable.QConstraintLayout_qclLeftTextMarginLeft, ConvertUtils.dp2px(25));//左边文字MarginLeft
...
## The stack of crash

java.lang.NullPointerException
	at sun.reflect.GeneratedMethodAccessor1571.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.blankj.utilcode.util.Utils.getApplicationByReflect(Utils.java:266)
	at com.blankj.utilcode.util.Utils.getApp(Utils.java:119)
	at com.blankj.utilcode.util.ConvertUtils.dp2px(ConvertUtils.java:584)
	at com.tgj.library.view.QConstraintLayout.<init>(QConstraintLayout.java:94)
	at sun.reflect.GeneratedConstructorAccessor495.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:403)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:186)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:144)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:309)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:418)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:429)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:333)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:323)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:394)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:200)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:572)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$5(RenderTask.java:698)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

## Screenshots

If applicable, add screenshots to help explain your problem.


Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
实际运行不会出错吧

**Comment by xietengyue** [comment]
> 实际运行不会出错吧

不会

**Comment by Blankj** [comment]
1.26.0 试试
