### ISSUE TITLE
ToastUtils在ColorOS 6 上报java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by HystrixWong** [Blankj/AndroidUtilCode#1059]
## ToastUtils在ColorOS 6 上报java.lang.NoSuchMethodError

弹出Toast报错，页面无任何显示

- The version of utilcode: 1.25.9
- The device: realme Q
- The version of device: API28 , compileSdkVersion 28

## The code of bug

```
 ToastUtils.showShort(message);
```

## The stack of crash

```
 W/System.err: java.lang.NoSuchFieldException: No field mActivityList in class Landroid/app/ActivityThread; (declaration of 'android.app.ActivityThread' appears in /system/framework/framework.jar)
 at java.lang.Class.getDeclaredField(Native Method)
at com.blankj.utilcode.util.Utils$ActivityLifecycleImpl.getTopActivityByReflect(Utils.java:488)
at com.blankj.utilcode.util.Utils$ActivityLifecycleImpl.getTopActivity(Utils.java:386)
at com.blankj.utilcode.util.Utils.getTopActivityOrApp(Utils.java:134)
at com.blankj.utilcode.util.ToastUtils$ToastWithoutNotification.realShow(ToastUtils.java:467)
at com.blankj.utilcode.util.ToastUtils$ToastWithoutNotification.access$800(ToastUtils.java:427)
at com.blankj.utilcode.util.ToastUtils$ToastWithoutNotification$2.run(ToastUtils.java:453)
at android.os.Handler.handleCallback(Handler.java:873)
```

## Screenshots

None

**Comment by Blankj** [comment]
你是在后台 show 的吧？没有 activity 直接 show 的吧？

**Comment by HystrixWong** [comment]
在Activity中show的，但是关闭了通知栏权限才会弹出的，没关闭是正常的

**Comment by Blankj** [comment]
错误就是没有通知权限，然后也没有 Activity 时你 show 了。

**Comment by Blankj** [comment]
这个也只是 catch 输出了异常，并没有崩溃呀

**Comment by HystrixWong** [comment]
是的，调用show方法无法弹Toast，Activity是正常显示的
