### ISSUE TITLE
BusUtils与Gson冲突, 不能通过编译

### ISSUE THREAD

**Issue by xiexin52k** [Blankj/AndroidUtilCode#1070]
如题, 新建项目, 一行代码都没写, 引入这两个依赖. 配置好bus之后, rebuild 结果报错, 不能通过编译
`
implementation 'com.blankj:utilcodex:1.25.9'
`
`
implementation 'com.google.code.gson:gson:2.8.6'
`

下面贴上Build过程中的报错信息
```java
Caused by: java.lang.RuntimeException
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
	at org.objectweb.asm.ClassReader.readModule(ClassReader.java:731)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at org.objectweb.asm.ClassReader$accept.call(Unknown Source)
	at com.blankj.bus.BusScan$_scanDir_closure1.doCall(BusScan.groovy:63)
	at com.blankj.bus.BusScan.scanDir(BusScan.groovy:41)
	at com.blankj.bus.BusScan$scanDir$0.callCurrent(Unknown Source)
	at com.blankj.bus.BusScan.scanJar(BusScan.groovy:25)
	at com.blankj.bus.BusScan$scanJar.call(Unknown Source)
	at com.blankj.bus.BusTransform$_transform_closure1$_closure5.doCall(BusTransform.groovy:96)
	at com.blankj.bus.BusTransform$_transform_closure1.doCall(BusTransform.groovy:78)
	at com.blankj.bus.BusTransform.transform(BusTransform.groovy:62)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:106)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction.doExecute(IncrementalTaskInputsTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
	at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:404)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:393)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:376)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:213)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:120)
	... 127 more
```

**Comment by xiexin52k** [comment]
使用`
'com.google.code.gson:gson:2.8.2'
`没有问题, 2.8.6就不行

**Comment by Blankj** [comment]
exclude 掉 gson 吧

**Comment by xiexin52k** [comment]
`
implementation ('com.blankj:utilcodex:1.25.9'){
        exclude group: "com.google.code.gson"
    }
    implementation 'com.google.code.gson:gson:2.8.6'
`
改成这样也没用呀

**Comment by Blankj** [comment]
去掉 bus 呢？

**Comment by xiexin52k** [comment]
```java
//apply plugin: "com.blankj.bus"
```
这个屏蔽掉的话, 能通过编译, 但是Bus就没用了, 不能发消息

**Comment by xiexin52k** [comment]
还有一个问题

```java
@BusUtils.Bus(tag = BusConfig.Transfer_Download_Progress_Config.TRANSFER_DOWNLOAD_PROGRESS_TAG, threadMode = BusUtils.ThreadMode.IO)
     public void onReceiveDownloadProcess(TransferDownloadProgressEvent downloadEvent) {
        // 方法体不能过长，会报错
        doReceiveAction(downloadEvent);
    }
```
具体多少行会报错我没统计, 反正我这边doReceiveAction函数里面有70行左右吧, 直接写在里面会不能通过编译

**Comment by Blankj** [comment]
直接微信单聊吧

**Comment by duguhanghai** [comment]
我这边也是 很郁闷 busutils 接收端方法体里面清了编译就过了 或者在包一个函数也可以 但是直接在里面写逻辑编译不过   String index out of range: -3

**Comment by Blankj** [comment]
@duguhanghai 你这个用 2.2 版本就行

**Comment by xiexin52k** [comment]
你这个问题~~给柯基发红包就可以解决~~
他到时候就会告诉你升级插件
`
classpath 'com.blankj:bus-gradle-plugin:2.3'
`
