### ISSUE TITLE
使用1.25.9版本在谷歌手机android10版本报以下错误

### ISSUE THREAD

**Issue by androidGhost** [Blankj/AndroidUtilCode#1099]
![utils](https://user-images.githubusercontent.com/9106628/69786080-a66bda80-11f4-11ea-95a2-131830176112.png)
java.lang.NoClassDefFoundError: com.blankj.utilcode.util.b
    at com.blankj.utilcode.util.b.a(AppUtils.java:418)
    at com.camera.function.main.ui.CameraPreviewActivity.onCreate(CameraPreviewActivity.java:535)
    at android.app.Activity.performCreate(Activity.java:7802)
    at android.app.Activity.performCreate(Activity.java:7791)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by androidGhost** [comment]
麻烦作者大大抽空看看，非常感谢

**Comment by Blankj** [comment]
解决了？
