### ISSUE TITLE
Request permission crash

### ISSUE THREAD

**Issue by XaviaDev** [Blankj/AndroidUtilCode#1114]
Crash in api 19 
```
    java.lang.NoSuchMethodError: android.provider.Settings.canDrawOverlays
        at com.blankj.utilcode.util.PermissionUtils.isGrantedDrawOverlays(PermissionUtils.java:145)
        at com.blankj.utilcode.util.PermissionUtils.requestDrawOverlays(PermissionUtils.java:150)

```
Please update 
```
 public static boolean isGrantedDrawOverlays() {
        return Settings.canDrawOverlays(Utils.getApp());
    }
```
to 
```
 public static boolean isGrantedDrawOverlays() {
        return Build.VERSION.SDK_INT < Build.VERSION_CODES.M || Settings.canDrawOverlays(Utils.getApp());
    }
```

**Comment by Blankj** [comment]
@RequiresApi(api = Build.VERSION_CODES.M)
我已经加了注解，是你调用的时候忽略没有处理
