### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by 626838956** [Blankj/AndroidUtilCode#1126]
java.lang.ExceptionInInitializerError
   at com.blankj.utilcode.util.NetworkUtils$NetworkChangedReceiver$3.run(Unknown Source)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5280)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
  Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.storage.StorageVolume[] android.os.storage.IMountService.getVolumeList()' on a null object reference
   at android.os.Environment.getStorageVolume(Environment.java:1224)
   at android.os.Environment.getExternalStorageState(Environment.java:1063)
   at android.os.Environment.getExternalStorageState(Environment.java:849)
   at com.blankj.utilcode.util.ak$a.(Unknown Source)
   at com.blankj.utilcode.util.ak$a.(Unknown Source)
   at com.blankj.utilcode.util.ak.(Unknown Source)

**Comment by Blankj** [comment]
信息太少了，定位不出来
