### ISSUE TITLE
AppUtils.installApp()安装报错，ActivityNotFoundException

### ISSUE THREAD

**Issue by gowcage** [Blankj/AndroidUtilCode#1142]
设备系统为8.1.0

错误日志：
2020-01-02 19:13:42.762 19861-19861/gqz.pager W/System.err: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://gqz.pager.utilcode.provider/external_path/Pager/Download/pinyin.apk typ=application/vnd.android.package-archive flg=0x10000001 }
2020-01-02 19:13:42.762 19861-19861/gqz.pager W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
2020-01-02 19:13:42.762 19861-19861/gqz.pager W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
2020-01-02 19:13:42.762 19861-19861/gqz.pager W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:878)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:855)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:372)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at com.blankj.utilcode.util.AppUtils.installApp(AppUtils.java:83)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at com.blankj.utilcode.util.AppUtils.installApp(AppUtils.java:71)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at gqz.jiuwu.imhelper.IMHelper.installIM(IMHelper.java:133)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at gqz.jiuwu.imhelper.IMGuideActivity.lambda$onCreate$1$IMGuideActivity(IMGuideActivity.java:74)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at gqz.jiuwu.imhelper.-$$Lambda$IMGuideActivity$ljk-M40pdS11Rt9SmDriWImRA10.onClick(Unknown Source:2)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at android.view.View.performClick(View.java:6294)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at android.view.View$PerformClick.run(View.java:24770)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at android.os.Looper.loop(Looper.java:164)
2020-01-02 19:13:42.763 19861-19861/gqz.pager W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
2020-01-02 19:13:42.764 19861-19861/gqz.pager W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-01-02 19:13:42.764 19861-19861/gqz.pager W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2020-01-02 19:13:42.764 19861-19861/gqz.pager W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Blankj** [comment]
用的什么版本？

**Comment by gowcage** [comment]
之前是用的1.23.7的，开始几次调试都可以调启安装，在其他地方加了一些代码和打印后突然不行了，很纳闷，后来又试了1.26.0，也不行，报一样的错。

**Comment by gowcage** [comment]
抱歉，找到原因了，是我这边的问题，不好意思，打扰了！
