### ISSUE TITLE
使用ZipUtils压缩异常java.util.zip.ZipException: No entries

### ISSUE THREAD

**Issue by liuhui19991** [Blankj/AndroidUtilCode#1161]
楼主好，使用压缩工具类时报了如下错，久久找不到原因，往解惑
~~~
java.util.zip.ZipException: No entries
     at java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:363)
     at com.example.alertdialog.ZipUtils.zipFiles(ZipUtils.java:115)
     at com.example.alertdialog.ZipUtils.zipFiles(ZipUtils.java:89)
     at com.example.alertdialog.MainActivity$4.onClick(MainActivity.java:124)
     at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loop(Looper.java:193)
     at android.app.ActivityThread.main(ActivityThread.java:6772)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
~~~
代码是这样的
~~~
 String path = Environment.getExternalStorageDirectory().getAbsolutePath() + "/DCIM/Camera";
                String des = Environment.getExternalStorageDirectory().getAbsolutePath() + "/picture.zip";
                ArrayList<File> arrayList = new ArrayList<>();
                for (File file : FileUtils.listFilesInDir(path)) {
                    arrayList.add(file);
                }
                try {
                    ZipUtils.zipFiles(arrayList, new File(des));
                } catch (IOException e) {
                    e.printStackTrace();
                }
~~~
path 目录下文件类型有MP4，jpg，png
是我使用方式不对吗？

**Comment by Blankj** [comment]
你拷贝我的工具类出去，然后把 `zos.finish();` 删掉试试看。

**Comment by liuhui19991** [comment]
我跟了后面的代码，后面有段出异常了，应该与finish无关，用的就是你的工具类，今天放假了等年后才能试，提前祝楼主新年快乐
有实例成功的代码贴下，我今天差不多所有压缩方法都调了，都没成功

**Comment by Blankj** [comment]
我单测是通过的哈，等你放假回来 debug 看看吧，也祝你新年快乐哈

**Comment by Blankj** [comment]
这个有后文吗？

**Comment by windfone** [comment]
问一下，ZipUtils.unzipFile("","") 怎么加加压成功的回调呀
