### ISSUE TITLE
UriUtils在小米手机上报错的问题

### ISSUE THREAD

**Issue by aheven** [Blankj/AndroidUtilCode#1170]
当前版本：1.25.9
手机型号：小米8

报错行：
`context.getContentResolver().query(
                uri, new String[]{"_data"}, selection, selectionArgs, null);`这句代码时报错

错误日志：
`java.lang.SecurityException: Permission Denial: opening provider com.miui.gallery.provider.GalleryOpenProvider from ProcessRecord{92fc74 2465:com.mall.ninecommunity/u0a631} (pid=2465, uid=10631) that is not exported from UID 10027
        at android.os.Parcel.readException(Parcel.java:2005)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4858)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:5963)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2540)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1796)
        at android.content.ContentResolver.query(ContentResolver.java:740)
        at android.content.ContentResolver.query(ContentResolver.java:705)
        at android.content.ContentResolver.query(ContentResolver.java:663)`

**Comment by Blankj** [comment]
这个 GalleryOpenProvider 没有 exported 吧？

**Comment by aheven** [comment]
这个GalleryOpenProvider是系统相册的Provider，`com.miui.gallery.provider`

**Comment by Blankj** [comment]
你启动相册需要加 uri 的 permission
```java
intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
```

**Comment by aheven** [comment]
添加了`intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);`依然报错，在华为,oppo手机上都没有问题，只是在这台机型上存在这个问题

**Comment by aheven** [comment]
有点类似这个问题：
https://stackoverflow.com/questions/50412179/permission-denial-opening-provider-com-miui-gallery-provider-galleryopenprovide

**Comment by aheven** [comment]
问题解决了，原因是由于我这边打开相册的时候启动了一个透明的activity进行中转，导致在小米手机上uri授权丢失，解决方法是取消activity中转。
