### ISSUE TITLE
gradle3.0.1 compile error

### ISSUE THREAD

**Issue by liweijieok** [Blankj/AndroidUtilCode#1198]
## Version
version: `1.26.0`
## The code of bug
```
Exception in thread "main" java.lang.IllegalArgumentException: Type without superclass: module-info
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visit(DefaultMethodClassFixer.java:80)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:113)
        at com.google.devtools.build.android.desugar.InterfaceDesugaring.visit(InterfaceDesugaring.java:97)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:621)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)
```

**Comment by liweijieok** [comment]
`1.25.9 ` is fine

**Comment by Blankj** [comment]
试试 1.27.0
