### ISSUE TITLE
项目集成utilscode和aspectj后编译报错

### ISSUE THREAD

**Issue by HyalwW** [Blankj/AndroidUtilCode#1199]
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
...
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at com.android.builder.dexing.JarClassFileInput.entries(JarClassFileInput.java:61)

**Comment by Blankj** [comment]
1.27.0 版本呢
