### ISSUE TITLE
EncryptUtils.encryptMD2ToString 报错

### ISSUE THREAD

**Issue by Wanchen7** [Blankj/AndroidUtilCode#1263]
## 描述 Bug

在设备上跑单元测试发现MD2跑不通，是不是MD2算法被移除了？

- AndroidUtilCode 的版本：1.29.0
- 出现 Bug 的设备型号：P30 PRO
- 设备的 Android 版本：API 29

## 相关代码
```
EncryptUtils.encryptMD2ToString("blankj")
```

## 异常堆栈

```
W/System.err: java.security.NoSuchAlgorithmException: MD2 MessageDigest not available
W/System.err:     at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
W/System.err:     at java.security.Security.getImpl(Security.java:628)
W/System.err:     at java.security.MessageDigest.getInstance(MessageDigest.java:197)
```

**Comment by Blankj** [comment]
是的，在 Android 上被移除了
