### ISSUE TITLE
java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by KnnethKong** [Blankj/AndroidUtilCode#1265]
## 描述 Bug
首先这个文件是存在的，
解压文件报错，当解压一个2.2GB的文件是出错。
是否和文件大小有关系，之前解压小文件没有问题。

- AndroidUtilCode 的版本： utilcode:1.29.0
- 出现 Bug 的设备型号：通常手机
- 设备的 Android 版本：

## 相关代码
    ZipUtils.unzipFile(file1, file2);

## 异常堆栈

2020-06-19 13:09:31.792 4214-4618/com.bfhd.enstudy W/System.err: java.util.zip.ZipException: error in opening zip file
2020-06-19 13:09:31.792 4214-4618/com.bfhd.enstudy W/System.err:     at java.util.zip.ZipFile.open(Native Method)
2020-06-19 13:09:31.792 4214-4618/com.bfhd.enstudy W/System.err:     at java.util.zip.ZipFile.<init>(ZipFile.java:238)
2020-06-19 13:09:31.792 4214-4618/com.bfhd.enstudy W/System.err:     at java.util.zip.ZipFile.<init>(ZipFile.java:152)
2020-06-19 13:09:31.792 4214-4618/com.bfhd.enstudy W/System.err:     at java.util.zip.ZipFile.<init>(ZipFile.java:166)
2020-06-19 13:09:31.792 4214-4618/com.bfhd.enstudy W/System.err:     at com.blankj.utilcode.util.ZipUtils.unzipFileByKeyword(ZipUtils.java:290)
2020-06-19 13:09:31.792 4214-4618/com.bfhd.enstudy W/System.err:     at com.blankj.utilcode.util.ZipUtils.unzipFile(ZipUtils.java:256)

**Comment by Blankj** [comment]
应该是 2.2 GB 转为字节超过 int 最大值导致的，客户端为啥要解压这么大的文件？

**Comment by Blankj** [comment]
可以分批次处理，每次不要超过2.2，之后再合起来

**Comment by KnnethKong** [comment]
好的

**Comment by KnnethKong** [comment]
好的 ，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Blankj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月19日(星期五) 下午2:41
收件人:&nbsp;"Blankj/AndroidUtilCode"<AndroidUtilCode@noreply.github.com&gt;;
抄送:&nbsp;"春风吹有灭"<kxf.kxf@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Blankj/AndroidUtilCode] java.util.zip.ZipException: error in opening zip file (#1265)





 
可以分批次处理，每次不要超过2.2，之后再合起来
