### ISSUE TITLE
uri2file,  出现NumerFormatException，程序挂掉

### ISSUE THREAD

**Issue by WPolly** [Blankj/AndroidUtilCode#1281]
## 描述 Bug

uriutils中uri2file方法调用崩掉。

- AndroidUtilCode 的版本：utilcodex:1.29.0
- 出现 Bug 的设备型号：oneplus 6T
- 设备的 Android 版本：API29

## 相关代码

File uri2File = UriUtils.uri2File(uri);

## 异常堆栈

Caused by: java.lang.NumberFormatException: For input string: "msf:1160391"
        at java.lang.Long.parseLong(Long.java:594)
        at java.lang.Long.valueOf(Long.java:808)
        at com.blankj.utilcode.util.UriUtils.uri2FileReal(UriUtils.java:197)
        at com.blankj.utilcode.util.UriUtils.uri2File(UriUtils.java:74)

**Comment by Blankj** [comment]
先升级看是否能解决

**Comment by WPolly** [comment]
> 先升级看是否能解决

写错了，是用的最新1.29.0版本出现的bug

**Comment by Blankj** [comment]
上下文呢，对什么 uri 进行处理？

**Comment by WPolly** [comment]
打开系统文件管理选择文件，获取到URI进行转文件操作，获取到的文件uri格式为：content://com.android.providers.downloads.documents/document/msf%3A1259026

**Comment by WPolly** [comment]
> 上下文呢，对什么 uri 进行处理？

打开系统文件管理选择文件，获取到URI进行转文件操作，获取到的文件uri格式为：content://com.android.providers.downloads.documents/document/msf%3A1259026

**Comment by JiZhi-Error** [comment]
https://blog.csdn.net/jingzz1/article/details/106188462/
建议参考，本人测试过

**Comment by Blankj** [comment]
新版本 1.30.0 已发布，已修复
