### ISSUE TITLE
Oppo CPH1819 toast的时候报异常。

### ISSUE THREAD

**Issue by nihaohebin** [Blankj/AndroidUtilCode#1290]
## Describe the bug

- The version of AndroidUtilCode: utilcode:1.28.4
- The device: oppo CPH1819
- The version of device:  android 9.0

## The code of bug

错误日志

/Resources: ColorStateList oppo:color/oppo_primary_text_dark has unresolved theme attributes! Consider using Resources.getColorStateList(int, Theme) or Context.getColorStateList(int).
    java.lang.RuntimeException
        at android.content.res.Resources.getColorStateList(Resources.java:1045)
        at skin.support.content.res.SkinCompatResources.getSkinColorStateList(SkinCompatResources.java:152)
        at skin.support.content.res.SkinCompatResources.getColorStateList(SkinCompatResources.java:244)
        at skin.support.widget.SkinCompatTextHelper.applyTextColorResource(SkinCompatTextHelper.java:127)
        at skin.support.widget.SkinCompatTextHelper.onSetTextAppearance(SkinCompatTextHelper.java:97)
        at skin.support.widget.SkinCompatTextView.setTextAppearance(SkinCompatTextView.java:49)
        at com.color.internal.widget.ColorToastLayout.onFinishInflate(ColorToastLayout.java:100)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:913)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:861)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.widget.Toast.makeText(Toast.java:310)
        at android.widget.Toast.makeText(Toast.java:296)
        at com.nono.android.common.utils.ToastUtils$ToastFactory.makeNormalToast(ToastUtils.java:467)
        at com.nono.android.common.utils.ToastUtils$ToastFactory.makeToast(ToastUtils.java:453)

**Comment by Blankj** [comment]
你这啥都不提供叫我怎么查？

**Comment by nihaohebin** [comment]
> 你这啥都不提供叫我怎么查？

咦，奇怪，我明明把异常详情和设备版本都填了。sorry，我再提一次

**Comment by nihaohebin** [comment]
> 你这啥都不提供叫我怎么查？

应该是我复制到注释里面去了。不好意思

**Comment by nihaohebin** [comment]
> 你这啥都不提供叫我怎么查

**Comment by Blankj** [comment]
好的

**Comment by nihaohebin** [comment]
> 好的

这个是不是我的问题。主题问题？可是看了下源码，我并没有设置什么主题之类的就是 调了一句tosast  showshort 一个string 字符串。其他都是源码默认的。奇怪。
