### ISSUE TITLE
ServiceUtils isServiceRunning 部分机型抛出 android.os.DeadSystemException

### ISSUE THREAD

**Issue by xuhaoyang** [Blankj/AndroidUtilCode#1291]
## 描述 Bug

简洁地描述下 Bug。

- AndroidUtilCode 的版本：所有版本(到1.29.0)
- 出现 Bug 的设备型号：samsung SM-G960F(s9) / samsung Note9还有其他机型 未统计
- 设备的 Android 版本：Android 9

## 相关代码

```
ServiceUtils.isServiceRunning(xxxx.class.getName())
```

## 异常堆栈

```
android.os.DeadSystemException
 Caused by: java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.ActivityManager.getRunningServices(ActivityManager.java:2696)
	at xxxx.ServiceUtils.isServiceRunning(SourceFile:2)
	at xxxxx.xxxxx$x.handleMessage(SourceFile:5)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8125)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

## 截图

如果有的话请添加屏幕截图以帮助解释问题。

## 处理建议

建议catch 这类错误 避免应用crash

**Comment by Blankj** [comment]
下版本加 catch

**Comment by Blankj** [comment]
新版本 1.30.0 已发布

**Comment by scsfwgy** [comment]
``
java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:273)
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:244)
	at com.blankj.utilcode.util.AppUtils.getAppVersionCode(AppUtils.java:536)
	at com.blankj.utilcode.util.AppUtils.getAppVersionCode(AppUtils.java:523)
``

@Blankj
