### ISSUE TITLE
KeyboardUtils.unregisterSoftInputChangedListener()调用报NullPointerException

### ISSUE THREAD

**Issue by langrenqing214** [Blankj/AndroidUtilCode#1292]
## 描述 Bug

简洁地描述下 Bug。

- AndroidUtilCode 的版本：
- 出现 Bug 的设备型号：多机型
- 设备的 Android 版本：多版本

## 相关代码

```
KeyboardUtils.unregisterSoftInputChangedListener()
```

## 异常堆栈

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.widget.FrameLayout.getTag(int)' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4603)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4621)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:44)
        at com.tencent.matrix.trace.hacker.ActivityThreadHacker$HackCallback.handleMessage(ActivityThreadHacker.java:118)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.widget.FrameLayout.getTag(int)' on a null object reference
        at com.blankj.utilcode.util.KeyboardUtils.unregisterSoftInputChangedListener(KeyboardUtils.java:236)
```

**Comment by Blankj** [comment]
下版本修复

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
