### ISSUE TITLE
DeviceUtils.getMacAddress(SourceFile:119) NullPointException

### ISSUE THREAD

**Issue by 2tu** [Blankj/AndroidUtilCode#1298]
## 描述 Bug

rt

- AndroidUtilCode 的版本：1.28.0
- 出现 Bug 的设备型号：vivo X7
- 设备的 Android 版本：5.1.1

## 异常堆栈

```
java.lang.NullPointerException: Attempt to invoke virtual method &#39;boolean java.lang.String.equals(java.lang.Object)&#39; on a null object reference
	at com.blankj.utilcode.util.DeviceUtils.getMacAddress(SourceFile:119)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5418)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by Blankj** [comment]
好的，下版本修复

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
