### ISSUE TITLE
1.29.0权限申请用户禁止权限后，无法打开系统权限设置页面

### ISSUE THREAD

**Issue by Tlioylc** [Blankj/AndroidUtilCode#1332]
## 描述 Bug
设备权限申请阶段，如果用户拒绝了，再次请求用户权限时，用户无法跳转系统权限设置页面

## 相关代码

```
   PermissionUtils.permission(permission)
                .rationale(new PermissionUtils.OnRationaleListener() {
                    @Override
                    public void rationale(UtilsTransActivity activity, ShouldRequest shouldRequest) {
                        showPermissionRationalDialog("为了更好的为您服务，需要您允许使用\""+permssionName+"\"权限", shouldRequest,permissionCallBack);
                    }
                })
                .callback(new PermissionUtils.FullCallback() {
                    @Override
                    public void onGranted(List<String> permissionsGranted) {
                        if (permissionCallBack != null) {
                            permissionCallBack.execute();
                        }
                    }

                    @Override
                    public void onDenied(List<String> permissionsDeniedForever, List<String> permissionsDenied) {
                        if (!permissionsDeniedForever.isEmpty()) {
                            showPermissionDeniedForeverDialog(permssionName, permissionCallBack);
                            return;
                        }
                        if (permissionCallBack != null) {
                            permissionCallBack.failed();
                        }
                    }
                })
                .request();



private void showPermissionRationalDialog(String msg, final PermissionUtils.OnRationaleListener.ShouldRequest shouldRequest,final PermissionCallBack permissionCallBack) {
        Activity activity = weakActivity.get();
        if(null == activity){
            return;
        }
        new BottomDialog.Builder(activity)
                .setContent(msg)
                .setPositiveText("确定")
                .setNegativeText("取消")
                .onPositive(new BottomDialog.ButtonCallback() {
                    @Override
                    public void onClick(@NonNull BottomDialog var1) {
                        shouldRequest.again(true);
                    }
                })
                .onNegative(new BottomDialog.ButtonCallback() {
                    @Override
                    public void onClick(@NonNull BottomDialog var1) {
                        if (permissionCallBack != null) {
                            permissionCallBack.failed();
                        }
                    }
                })
                .show();
    }
```

## 异常堆栈

```
2020-09-21 16:09:59.190 5805-5805/? I/GrantPermissionsActivity: No package: null
    android.content.pm.PackageManager$NameNotFoundException
        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:195)
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:164)
        at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.getCallingPackageInfo(GrantPermissionsActivity.java:1016)
        at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.onCreate(GrantPermissionsActivity.java:386)
        at android.app.Activity.performCreate(Activity.java:7820)
        at android.app.Activity.performCreate(Activity.java:7809)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3363)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3527)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by Tlioylc** [comment]
确定是Dialog导致的无法跳转，没有定位到原因，在旧版本的util库上是可以跳转的- -，这边先处理了
