### ISSUE TITLE
toastutil在mvvm封装中显示闪退

### ISSUE THREAD

**Issue by fengyz2001** [Blankj/AndroidUtilCode#1333]
## 描述 Bug
用了1.26.0 和1.29.0一样闪退
在封装中   ToastUtils.showShort("") 闪退

## 异常堆栈
 Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:724)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:792)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.widget.Toast.makeText(Toast.java:284)
        at android.widget.Toast.makeText(Toast.java:270)
        at com.blankj.utilcode.util.ToastUtils$ToastFactory.makeNormalToast(ToastUtils.java:374)
        at com.blankj.utilcode.util.ToastUtils$ToastFactory.makeToast(ToastUtils.java:354)
        at com.blankj.utilcode.util.ToastUtils$1.run(ToastUtils.java:263)
        at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:69)
        at com.blankj.utilcode.util.UtilsBridge.runOnUiThread(UtilsBridge.java:520)
        at com.blankj.utilcode.util.ToastUtils.show(ToastUtils.java:258)
        at com.blankj.utilcode.util.ToastUtils.show(ToastUtils.java:254)
        at com.blankj.utilcode.util.ToastUtils.showShort(ToastUtils.java:141)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x11100e1 a=-1}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:948)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:932)
        at android.view.View.<init>(View.java:5023)
        at android.view.ViewGroup.<init>(ViewGroup.java:659)
        at android.widget.LinearLayout.<init>(LinearLayout.java:244)
        at android.widget.LinearLayout.<init>(LinearLayout.java:240)
        at android.widget.LinearLayout.<init>(LinearLayout.java:236)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:651) 
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:724) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:792) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:496) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at android.widget.Toast.makeText(Toast.java:284) 
        at android.widget.Toast.makeText(Toast.java:270) 
        at com.blankj.utilcode.util.ToastUtils$ToastFactory.makeNormalToast(ToastUtils.java:374) 
        at com.blankj.utilcode.util.ToastUtils$ToastFactory.makeToast(ToastUtils.java:354) 
        at com.blankj.utilcode.util.ToastUtils$1.run(ToastUtils.java:263) 
        at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:69) 
        at com.blankj.utilcode.util.UtilsBridge.runOnUiThread(UtilsBridge.java:520) 
        at com.blankj.utilcode.util.ToastUtils.show(ToastUtils.java:258) 
        at com.blankj.utilcode.util.ToastUtils.show(ToastUtils.java:254) 
        at com.blankj.utilcode.util.ToastUtils.showShort(ToastUtils.java:141) 
        at com.xinya.lhposv7.ui.main.SynDataActivity$startObserve$1.onChanged(SynDataActivity.kt:32) 
        at com.xinya.lhposv7.ui.main.SynDataActivity$startObserve$1.onChanged(SynDataActivity.kt:23) 
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131) 
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149) 
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307) 
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) 
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6823) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by Blankj** [comment]
新版本 1.30.0 已发布，ToastUtils 已无敌
