### ISSUE TITLE
闪退了 帮忙看下吧

### ISSUE THREAD

**Issue by troyccc** [Blankj/AndroidUtilCode#1342]
java.lang.IllegalAccessError: Illegal class access: 'com.blankj.utilcode.util.Utils$ActivityLifecycleImpl' attempting to access 'com.blankj.utilcode.util.Utils$ActivityLifecycleImpl$1' (declaration of 'com.blankj.utilcode.util.Utils$ActivityLifecycleImpl' appears in base.apk)
	at com.blankj.utilcode.util.Utils$ActivityLifecycleImpl.processHideSoftInputOnActivityDestroy(Utils.java:581)
	at com.blankj.utilcode.util.Utils$ActivityLifecycleImpl.onActivityResumed(Utils.java:490)
	at android.app.Application.dispatchActivityResumed(Application.java:443)
	at android.app.Activity.dispatchActivityResumed(Activity.java:1315)
	at android.app.Activity.onResume(Activity.java:1859)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:456)
	at com.yyy.b.ui.main.MainActivity.onResume(MainActivity.java:127)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1465)
	at android.app.Activity.performResume(Activity.java:8223)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4779)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4832)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
	at com.wanjian.cockroach.Cockroach$2.handleMessage(Cockroach.java:116)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by Blankj** [comment]
怎么不按照我给的模板写 bug 呢，这个错误我看不出来什么，是部分机型还是怎么

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
