### ISSUE TITLE
ActivityUtils.finishActivity() 方法执行错误

### ISSUE THREAD

**Issue by CleverSJX** [Blankj/AndroidUtilCode#1369]
## ActivityUtils.finishActivity() 方法执行错误

- AndroidUtilCode 的版本：    'com.blankj:utilcodex:1.29.0'

## 相关代码

```
ActivityUtils.finishActivity(MultiPlayActivity.class);

```

## 异常堆栈

```
java.util.ConcurrentModificationException: null
	at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
	at com.blankj.utilcode.util.ActivityUtils.finishActivity(ActivityUtils.java:1611)
	at com.blankj.utilcode.util.ActivityUtils.finishActivity(ActivityUtils.java:1599)
	at com.longjing.helper.PlayHelper.start(PlayHelper.java:34)
	at com.longjing.jsapi.PlayApi.start(PlayApi.java:17)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.longjing.jsbridge.DWebView$InnerJavascriptInterface.call(DWebView.java:189)
	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:51)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by Blankj** [comment]
切到主线程调用试试看
