### ISSUE TITLE
获取mac地址空指针

### ISSUE THREAD

**Issue by CleverSJX** [Blankj/AndroidUtilCode#1370]
## DeviceUtils.getMacAddress(); 空指针

- AndroidUtilCode 的版本：com.blankj:utilcodex:1.29.0

## 相关代码

```
DeviceUtils.getMacAddress();
```

## 异常堆栈
```
java.lang.reflect.InvocationTargetException: null
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.longjing.jsbridge.DWebView$InnerJavascriptInterface.call(DWebView.java:189)
	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:51)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.blankj.utilcode.util.DeviceUtils.getMacAddress(DeviceUtils.java:120)
	at com.longjing.jsapi.SystemApi.deviceInfo(SystemApi.java:48)
	... 8 common frames omitted
```

**Comment by Blankj** [comment]
有问题第一时间升级版本呀，不过 Mac 地址 高版本是不固定的了已经

**Comment by CleverSJX** [comment]
> 高版本是不固定的了

好的谢谢~,是的 都虚拟mac了,坑呀
