### ISSUE TITLE
急急急java.lang.SecurityException: getPackageUid: Neither user 1010142 nor current process has android.permission.INTERACT_ACROSS_USERS.

### ISSUE THREAD

**Issue by dengdaoyus** [Blankj/AndroidUtilCode#1375]
java.lang.SecurityException: getPackageUid: Neither user 1010142 nor current process has android.permission.INTERACT_ACROSS_USERS.
    at android.os.Parcel.createException(Parcel.java:2071)
    at android.os.Parcel.readException(Parcel.java:2039)
    at android.os.Parcel.readException(Parcel.java:1987)
    at com.huawei.multimedia.audioengine.IHwAudioKaraokeFeature$Stub$Proxy.init(IHwAudioKaraokeFeature.java:6)
    at com.huawei.multimedia.audiokit.interfaces.HwAudioKaraokeFeatureKit.serviceInit(HwAudioKaraokeFeatureKit.java:2)
    at com.huawei.multimedia.audiokit.interfaces.HwAudioKaraokeFeatureKit.access$400(HwAudioKaraokeFeatureKit.java:1)
    at com.huawei.multimedia.audiokit.interfaces.HwAudioKaraokeFeatureKit$1.onServiceConnected(HwAudioKaraokeFeatureKit.java:6)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2037)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2069)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8347)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
Back traces ends.

**Comment by dengdaoyus** [comment]
出现的几率非常大非常大

**Comment by Blankj** [comment]
？？ 有我什么事情

**Comment by MissDelia** [comment]
兄弟你这就贴了个任务栈其它什么也不说，组织上很难帮助你什么啊
