### ISSUE TITLE
NullPointerException   ThreadUtils

### ISSUE THREAD

**Issue by lhyAndroid** [Blankj/AndroidUtilCode#1415]
## 描述 Bug

简洁地描述下 Bug。
ThreadUtils timeoutListener nullpointer
## 异常堆栈
```
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.xunyue.adsdk.utils.ThreadUtils$Task$OnTimeoutListener.onTimeout()' on a null object reference
        at com.xunyue.adsdk.utils.ThreadUtils$Task$1.run(ThreadUtils.java:1225)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)
```
timeout() 中的 onDone 方法 会将 mTimeoutListener 设置为空 导致mTimeoutListener.onTimeout(); 空指针

**Comment by SpandanBasu** [comment]
I am a beginner, I want to work on this issue

**Comment by Blankj** [comment]
1.30.6 版本已修复
