### ISSUE TITLE
android解压报错 ZipUtils.unzipFileByKeyword(ZipUtils.java:295)

### ISSUE THREAD

**Issue by haonan1** [Blankj/AndroidUtilCode#1447]
## 描述 Bug

简洁地描述下 Bug。

- AndroidUtilCode 的版本：
- 出现 Bug 的设备型号：
- 设备的 Android 版本：

#00 pc 00011308 /apex/com.android.runtime/lib/libopenjdk.so (newEntry+63)
2.#01 pc 0001168f /apex/com.android.runtime/lib/libopenjdk.so (ZIP_GetNextEntry+32)
3.#02 pc 0000f20b /apex/com.android.runtime/lib/libopenjdk.so (ZipFile_getNextEntry+6)
4.#03 pc 000eec59 /system/framework/arm/boot.oat (art_jni_trampoline+112)
5.#04 pc 0025c929 /system/framework/arm/boot.oat (java.util.zip.ZipFile$ZipEntryIterator.next+144)
6.#05 pc 0001b84d /memfd:/jit-cache (deleted)
7.at java.util.zip.ZipFile.getNextEntry(Native method)
8.at java.util.zip.ZipFile.access$500(ZipFile.java:64)
9.at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:568)
10.at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:559)
11.at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:540)
12.at com.blankj.utilcode.util.ZipUtils.unzipFileByKeyword(ZipUtils.java:295)
13.at com.blankj.utilcode.util.ZipUtils.unzipFile(ZipUtils.java:256)
14.at com.sccba.emas.main.manager.DownLoadZipManager$downloadZip$1.invokeSuspend(DownLoadZipManager.kt:44)
15.at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
16.at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
17.at android.os.Handler.handleCallback(Handler.java:900)
18.at android.os.Handler.dispatchMessage(Handler.java:103)
19.at android.os.Looper.loop(Looper.java:219)
20.at android.app.ActivityThread.main(ActivityThread.java:8347)
21.at java.lang.reflect.Method.invoke(Native method)
22.at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
23.at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by AriaLyy** [comment]
我也遇到了同样的问题，楼主解决了吗？

**Comment by ATeamMac2014** [comment]
注意文件读取过程中，不要写zip文件，不然会引入崩溃

**Comment by xuwanjin** [comment]
我也遇到了同样的问题.

**Comment by xuwanjin** [comment]
解决了，原来我对文件 就是上面的操作。 注意文件读取过程中，不要写zip文件，不然会引入崩溃。 
谢谢了 @ATeamMac2014
