### ISSUE TITLE
Toast.getView() returns null on Android 11 (API 30)

### ISSUE THREAD

**Issue by gauravarora90** [Blankj/AndroidUtilCode#1449]
Toast.getView() returns null on Android 11 (API 30)

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at com.blankj.utilcode.util.ToastUtils$1.run(ToastUtils.java:213)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8456)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)

**Comment by Blankj** [comment]
update the version
