### ISSUE TITLE
Location权限在6.0系统崩溃的问题

### ISSUE THREAD

**Issue by li-xiaojun** [Blankj/AndroidUtilCode#1511]
## Describe the bug
申请LOCATION权限，在6.0系统崩溃，主要是找不到android.permission.ACCESS_BACKGROUND_LOCATION

## The code of bug
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.seallive.androidapp/com.blankj.utilcode.util.UtilsTransActivity}: java.lang.IllegalArgumentException: Unknown permission: android.permission.ACCESS_BACKGROUND_LOCATION
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3961)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4004)
        at android.app.ActivityThread.access$1600(ActivityThread.java:170)
```

**Comment by FeiMAndroid** [comment]
同样的错误，机型：OPPO R9sk Android版本：6.0.1

**Comment by clbDream** [comment]
这个权限在10还是11上才有的,6.0上肯定找不到啊
