### ISSUE TITLE
截图内存溢出

### ISSUE THREAD

**Issue by CleverSJX** [Blankj/AndroidUtilCode#1518]
## 截图内存溢出

截图内存溢出

- AndroidUtilCode 的版本：implementation 'com.blankj:utilcodex:1.30.6'
- 设备的 Android 版本：4.4.2

## 相关代码

```java
ScreenUtils.screenShot(ActivityUtils.getTopActivity())
```

## 异常堆栈

```
************* Crash Head ****************

java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
	at com.blankj.utilcode.util.ImageUtils.view2Bitmap(ImageUtils.java:202)
	at com.blankj.utilcode.util.UtilsBridge.view2Bitmap(UtilsBridge.java:358)
	at com.blankj.utilcode.util.ScreenUtils.screenShot(ScreenUtils.java:240)
	at com.blankj.utilcode.util.ScreenUtils.screenShot(ScreenUtils.java:228)
	at com.longjing.util.system.NoSignSystemUtils.screenshot(NoSignSystemUtils.java:23)
	at com.longjing.util.system.AbstractSystemUtils$1.run(AbstractSystemUtils.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

java.lang.OutOfMemoryError: null
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
	at com.blankj.utilcode.util.ImageUtils.view2Bitmap(ImageUtils.java:202)
	at com.blankj.utilcode.util.UtilsBridge.view2Bitmap(UtilsBridge.java:358)
	at com.blankj.utilcode.util.ScreenUtils.screenShot(ScreenUtils.java:240)
	at com.blankj.utilcode.util.ScreenUtils.screenShot(ScreenUtils.java:228)
	at com.longjing.util.system.NoSignSystemUtils.screenshot(NoSignSystemUtils.java:23)
	at com.longjing.util.system.AbstractSystemUtils$1.run(AbstractSystemUtils.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by showdy** [comment]
截图支持surfaceview texttureview吗
