### ISSUE TITLE
打开应用崩溃

### ISSUE THREAD

**Issue by 15615833080** [Blankj/AndroidUtilCode#1554]
## 描述 Bug
启动应用崩溃，报Missing android.support.FILE_PROVIDER_PATHS meta-data错误
- AndroidUtilCode 的版本：1.30.6
- 设备的 Android 版本：API 29 

## 相关代码

Unable to get provider com.blankj.utilcode.util.UtilsFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data

## 异常堆栈

10-12 14:36:18.046  8977  8977 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.blankj.utilcode.util.UtilsFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6470)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6012)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5927)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:204)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6747)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:669)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:635)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at androidx.core.content.FileProvider.attachInfo(FileProvider.java:416)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6465)
10-12 14:36:18.046  8977  8977 E AndroidRuntime: 	... 10 more
10-12 14:36:18.049  8977  8996 D WtManager: SystemEventManager init

**Comment by zhonghaojie** [comment]
老哥你解决了么
