### ISSUE TITLE
API 23 ACCESS_BACKGROUND_LOCATION 权限请求报错

### ISSUE THREAD

**Issue by zhuxiaoxue** [Blankj/AndroidUtilCode#1566]
## 描述 Bug

找不到权限，崩溃

- AndroidUtilCode 的版本：utilcodex:1.30.6
- 出现 Bug 的设备型号：HUAWEI PLK-T100
- 设备的 Android 版本：API23

## 相关代码
manifest:
“android:name="android.permission.ACCESS_BACKGROUND_LOCATION"”
code:
PermissionUtils.permissionGroup(
                PermissionConstants.PHONE,
                PermissionConstants.LOCATION,
                PermissionConstants.SMS,
                PermissionConstants.STORAGE
        ).callback(new PermissionUtils.SingleCallback() {
            @Override
            public void callback(boolean isAllGranted, @NonNull List<String> granted, @NonNull List<String> deniedForever, @NonNull List<String> denied) {
                //
            }
        }).request();
## 异常堆栈
java.lang.IllegalArgumentException: Unknown permission: android.permission.ACCESS_BACKGROUND_LOCATION
    at com.android.server.pm.PackageManagerService.getPermissionFlags(PackageManagerService.java:3881)
    at com.android.server.pm.PackageManagerService.shouldShowRequestPermissionRationale(PackageManagerService.java:4027)
    at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:475)
    at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:2807)
    at com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:510)
    at android.os.Binder.execTransact(Binder.java:453)

**Comment by Sum-sdl** [comment]
低版本系统不兼容后台权限，需要区分处理
