### ISSUE TITLE
com.android.tools.r8.internal.b xxx is defined multiple times

### ISSUE THREAD

**Issue by wy353208214** [Blankj/AndroidUtilCode#1567]
## 无法Build

Kotlin项目中添加：`implementation 'com.blankj:utilcodex:1.30.6'`
编译报错，提示重复定义。

- AndroidUtilCode 的版本：utilcodex:1.30.6
- 编译环境：Android Studio 2020.3.1
- Gradle：7.0.3

### app：build.gradle
```groovy
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'com.alibaba.arouter'
}

kapt {
    arguments {
        arg("AROUTER_MODULE_NAME", project.getName())
    }
}

android {
    compileSdk 31

    defaultConfig {
        applicationId "hackyang.com.xxx"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.4.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    implementation 'com.jakewharton:butterknife:10.2.3'
    kapt "com.jakewharton:butterknife-compiler:10.2.3"

    implementation 'com.alibaba:arouter-api:1.5.2'
    kapt 'com.alibaba:arouter-compiler:1.5.2'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'com.wdullaer:materialdatetimepicker:4.2.3'
    implementation 'com.github.li-xiaojun:XPopup:2.6.7'
    implementation 'com.squareup.okhttp3:okhttp:4.9.2'
    implementation 'io.reactivex.rxjava3:rxkotlin:3.0.1'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    implementation 'io.reactivex.rxjava3:rxjava:3.0.0'

    implementation 'com.blankj:utilcodex:1.30.6'

}
```
### project：build.gradle
```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.3"
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31'
        classpath 'com.jakewharton:butterknife-gradle-plugin:10.2.3'
        classpath "com.alibaba:arouter-register:1.0.2"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
````

## 编译日志

```java
> Task :app:mergeProjectDexDebug FAILED
AGPBI: {"kind":"error","text":"Type kotlinx.android.extensions.CacheImplementation$Companion is defined multiple times: /Users/steven/Dev_Project/android/QpidNetworkKotlin/app/build/intermediates/mixed_scope_dex_archive/debug/out/273dbbe9476b1a97367218ccc76a56f7ff5c0a7de63d850b82bfb7a1dcfe01a7_0.jar:classes.dex, /Users/steven/Dev_Project/android/QpidNetworkKotlin/app/build/intermediates/mixed_scope_dex_archive/debug/out/975dab97d8aa780bc8d1af8efd66ba121c35c709537308d5742e812c46b126c0_0.jar:classes.dex","sources":[{"file":"/Users/steven/Dev_Project/android/QpidNetworkKotlin/app/build/intermediates/mixed_scope_dex_archive/debug/out/273dbbe9476b1a97367218ccc76a56f7ff5c0a7de63d850b82bfb7a1dcfe01a7_0.jar"}],"tool":"D8"}
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type kotlinx.android.extensions.CacheImplementation$Companion is defined multiple times: /Users/steven/Dev_Project/android/QpidNetworkKotlin/app/build/intermediates/mixed_scope_dex_archive/debug/out/273dbbe9476b1a97367218ccc76a56f7ff5c0a7de63d850b82bfb7a1dcfe01a7_0.jar:classes.dex, /Users/steven/Dev_Project/android/QpidNetworkKotlin/app/build/intermediates/mixed_scope_dex_archive/debug/out/975dab97d8aa780bc8d1af8efd66ba121c35c709537308d5742e812c46b126c0_0.jar:classes.dex
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:151)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:138)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:863)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:809)
	at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/steven/Dev_Project/android/QpidNetworkKotlin/app/build/intermediates/mixed_scope_dex_archive/debug/out/273dbbe9476b1a97367218ccc76a56f7ff5c0a7de63d850b82bfb7a1dcfe01a7_0.jar:classes.dex
	at Version.fakeStackEntry(Version_3.0.73.java:0)
	at com.android.tools.r8.utils.w.a(SourceFile:68)
	at com.android.tools.r8.utils.w.a(SourceFile:28)
	at com.android.tools.r8.utils.w.a(SourceFile:27)
	at com.android.tools.r8.utils.w.b(SourceFile:3)
	at com.android.tools.r8.D8.run(D8.java:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:136)
	... 35 more
Caused by: com.android.tools.r8.internal.b: Type kotlinx.android.extensions.CacheImplementation$Companion is defined multiple times: /Users/steven/Dev_Project/android/QpidNetworkKotlin/app/build/intermediates/mixed_scope_dex_archive/debug/out/273dbbe9476b1a97367218ccc76a56f7ff5c0a7de63d850b82bfb7a1dcfe01a7_0.jar:classes.dex, /Users/steven/Dev_Project/android/QpidNetworkKotlin/app/build/intermediates/mixed_scope_dex_archive/debug/out/975dab97d8aa780bc8d1af8efd66ba121c35c709537308d5742e812c46b126c0_0.jar:classes.dex
	at com.android.tools.r8.internal.UA.a(SourceFile:14)
	at com.android.tools.r8.internal.UA.a(SourceFile:22)
	at com.android.tools.r8.internal.Fw.b(SourceFile:6)
	at com.android.tools.r8.internal.Fw.a(SourceFile:23)
	at com.android.tools.r8.internal.Fw.a(SourceFile:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at com.android.tools.r8.internal.Fw.a(SourceFile:6)
	at com.android.tools.r8.graph.I0$c.f(SourceFile:3)
	at com.android.tools.r8.dex.a.a(SourceFile:94)
	at com.android.tools.r8.dex.a.a(SourceFile:23)
	at com.android.tools.r8.D8.a(D8.java:21)
	at com.android.tools.r8.D8.d(D8.java:11)
	at com.android.tools.r8.D8.b(D8.java:1)
	at com.android.tools.r8.utils.w.a(SourceFile:24)
	... 38 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeProjectDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type kotlinx.android.extensions.CacheImplementation$Companion is defined multiple times: /Users/steven/Dev_Project/android/QpidNetworkKotlin/app/build/intermediates/mixed_scope_dex_archive/debug/out/273dbbe9476b1a97367218ccc76a56f7ff5c0a7de63d850b82bfb7a1dcfe01a7_0.jar:classes.dex, /Users/steven/Dev_Project/android/QpidNetworkKotlin/app/build/intermediates/mixed_scope_dex_archive/debug/out/975dab97d8aa780bc8d1af8efd66ba121c35c709537308d5742e812c46b126c0_0.jar:classes.dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by wy353208214** [comment]
估计没人维护了，算了，已经自己解决，重复依赖问题，添加exclude：
` exclude group:'org.jetbrains.kotlin', module: 'kotlin-android-extensions-runtime'`

**Comment by nowtf** [comment]
> 你在质疑我？

xswl ，up 主一脸懵逼
