### ISSUE TITLE
切换语言闪退

### ISSUE THREAD

**Issue by Andy957** [Blankj/AndroidUtilCode#1604]
## 描述 Bug
切换语言闪退

- AndroidUtilCode 的版本：1.31.0
- 出现 Bug 的设备型号：三星Note20u
- 设备的 Android 版本：API 31

## 相关代码

LanguageUtils.applyLanguage(Locale("zh_rCN"), false)

## 异常堆栈

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.recreate()' on a null object reference
        at com.blankj.utilcode.util.LanguageUtils.restart(LanguageUtils.java:96)
        at com.blankj.utilcode.util.LanguageUtils.access$000(LanguageUtils.java:24)
        at com.blankj.utilcode.util.LanguageUtils$1.accept(LanguageUtils.java:82)
        at com.blankj.utilcode.util.LanguageUtils$1.accept(LanguageUtils.java:78)
        at com.blankj.utilcode.util.LanguageUtils.pollCheckAppContextLocal(LanguageUtils.java:186)
        at com.blankj.utilcode.util.LanguageUtils$2.run(LanguageUtils.java:192)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8641)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

**Comment by Andy957** [comment]
![image](https://user-images.githubusercontent.com/52651185/154910749-2b2484f6-4e29-4d9c-9d2a-93eeefc1cd63.png)
