### ISSUE TITLE
安卓4.4.2报错

### ISSUE THREAD

**Issue by duguhanghai** [Blankj/AndroidUtilCode#1636]
使用版本     com.blankj:utilcodex:1.31.0

2022-04-25 19:35:34.140 5415-5415/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.landleaf.screenStandard, PID: 5415
    java.lang.RuntimeException: Unable to get provider com.blankj.utilcode.util.UtilsFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.UtilsFileProvider" on path: DexPathList[[zip file "/data/app/com.landleaf.screenStandard-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.landleaf.screenStandard-1, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.UtilsFileProvider" on path: DexPathList[[zip file "/data/app/com.landleaf.screenStandard-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.landleaf.screenStandard-1, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4778)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by duguhanghai** [comment]
其中在高版本没有问题,拆分包:
androidx.multidex:multidex:2.0.0'

**Comment by Yuanxilin** [comment]
在4.4的安卓遇到一模一样的问题，现在有解决方法吗

**Comment by duguhanghai** [comment]
我的安卓软件版本可能有点奇怪,主要是在myApplicaiton中,定位问题后初始化中改动了MultiDex.install的入参即可.


protected void attachBaseContext(Context base) {
    MultiDex.install(base);
    super.attachBaseContext(base);
}


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年5月10日 16:15
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Blankj/AndroidUtilCode] 安卓4.4.2报错 (Issue #1636)


在4.4的安卓遇到一模一样的问题，现在有解决方法吗

―
