### ISSUE TITLE
PhoneUtils崩溃

### ISSUE THREAD

**Issue by tongzifang** [Blankj/AndroidUtilCode#1659]
## 描述 Bug

简洁地描述下 Bug。
在一些没有拨号盘的设备使用PhoneUtils.dial会崩溃,像商米设备,手持的pos,或者直接虚拟机应该也是

- AndroidUtilCode 的版本： 
 
com.blankj:utilcodex:1.31.0

## 相关代码

 PhoneUtils.dial()

## 异常堆栈

ActivityManager: Activity Manager Crash
    java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo android.content.pm.ComponentInfo.applicationInfo' on a null object reference
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1559)
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1153)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4275)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4262)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2790)
        at android.os.Binder.execTransact(Binder.java:458)
```
put the stack of crash here

**Comment by tongzifang** [comment]
这个是阿里云的
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.DIAL dat=tel:xxxxxxxxxxx flg=0x10000000 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
	at android.app.ContextImpl.startActivity(ContextImpl.java:791)
	at android.app.ContextImpl.startActivity(ContextImpl.java:768)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
	at com.blankj.utilcode.util.PhoneUtils.dial(PhoneUtils.java:294)

**Comment by shouzhong** [comment]
可能某些设备没有拨号功能，这个估计得自己捕获下异常
