### ISSUE TITLE
java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by leonard-kawhi** [Blankj/AndroidUtilCode#1701]
## 描述 Bug

简洁地描述下 Bug。

- AndroidUtilCode 的版本：1.30.6
- 出现 Bug 的设备型号：
- 设备的 Android 版本：android 7.1

## 相关代码
ZipUtils.unzipFile(zipFile, destDir);

## 异常堆栈
 at java.util.zip.ZipFile.open(Native Method)
2022-09-26 18:09:14.389 10305-10305/? W/System.err:     at java.util.zip.ZipFile.<init>(ZipFile.java:225)
2022-09-26 18:09:14.389 10305-10305/? W/System.err:     at java.util.zip.ZipFile.<init>(ZipFile.java:148)
2022-09-26 18:09:14.390 10305-10305/? W/System.err:     at java.util.zip.ZipFile.<init>(ZipFile.java:162)
2022-09-26 18:09:14.390 10305-10305/? W/System.err:     at com.blankj.utilcode.util.ZipUtils.unzipFileByKeyword(ZipUtils.java:290)
2022-09-26 18:09:14.390 10305-10305/? W/System.err:     at com.blankj.utilcode.util.ZipUtils.unzipFile(ZipUtils.java:256)

**Comment by DaviVilarinho** [comment]
Was that the full stack trace? Could you provide us the zip you're dealing with?
