### ISSUE TITLE
在Activity中使用ToastUtils后finish当前activity,控制台会提示内存泄漏,用原生Toast.maketext就不会是咋回事呢?

### ISSUE THREAD

**Issue by roybill** [Blankj/AndroidUtilCode#1801]
打印的泄漏日志:
android.view.WindowLeaked: Activity com.bank.account.BuyActivity has leaked window android.widget.ImageView{b3912b1 V.ED..... ......ID 0,0-296,146} that was originally added here
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1038)
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1022)
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:401)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:154)
                                                                                                    	at com.blankj.utilcode.util.ToastUtils$WindowManagerToast.show(ToastUtils.java:630)
                                                                                                    	at com.blankj.utilcode.util.ToastUtils$ActivityToast.showWithActivityWindow(ToastUtils.java:739)
                                                                                                    	at com.blankj.utilcode.util.ToastUtils$ActivityToast.show(ToastUtils.java:680)
                                                                                                    	at com.blankj.utilcode.util.ToastUtils$2.run(ToastUtils.java:494)
                                                                                                    	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:70)
                                                                                                    	at com.blankj.utilcode.util.UtilsBridge.runOnUiThread(UtilsBridge.java:554)
                                                                                                    	at com.blankj.utilcode.util.ToastUtils.show(ToastUtils.java:483)
                                                                                                    	at com.blankj.utilcode.util.ToastUtils.show(ToastUtils.java:472)
                                                                                                    	at com.blankj.utilcode.util.ToastUtils.showShort(ToastUtils.java:412)

**Comment by 1041411123** [comment]
一样的问题，有内存泄漏

**Comment by zhibo-tech** [comment]
一样的问题,有内存泄漏问题

**Comment by zhibo-tech** [comment]
@Blankj

**Comment by OneGreenHand-LXH** [comment]
在页面销毁的时候调用ToastUtils.cancel();
但是会取消吐司

**Comment by jerry9433** [comment]
顶一个

**Comment by xrn1997** [comment]
加一，希望修复

**Comment by 708848373** [comment]
+1，不知有没有新的变化或者优化；

**Comment by iFCoder** [comment]
一样的问题,有内存泄漏问题

**Comment by 708848373** [comment]
这是来自QQ邮箱的自动回复邮件。你好，收到这个自动回复就表示我已经收到你的邮件了，如有需要我会尽快给你回复。
