### ISSUE TITLE
activityutils无效

### ISSUE THREAD

**Issue by stoneLee81** [Blankj/AndroidUtilCode#225]
按照demo里的方法，打开一个activity,好像无效，packagename,classname肯定是传过来了且没错误
ActivityUtils.startActivity(bundle, C.ACTIVITY.PackageName, actiityName);

**Comment by stoneLee81** [comment]
1.3.6版本是没问题的，昨天升到了1.7.1就发现点击打开无效

**Comment by stoneLee81** [comment]
java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = trip.com.haowma.model.local.Crital)
                                                  at android.os.Parcel.readSerializable(Parcel.java:2630)
                                                  at android.os.Parcel.readValue(Parcel.java:2416)
                                                  at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
                                                  at android.os.BaseBundle.unparcel(BaseBundle.java:269)
                                                  at android.os.BaseBundle.getString(BaseBundle.java:992)
                                                  at android.app.ActivityOptions.<init>(ActivityOptions.java:803)
                                                  at android.app.ActivityOptions.fromBundle(ActivityOptions.java:1008)
                                                  at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:795)
                                                  at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5210)
                                                  at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5012)
                                                  at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:169)
                                                  at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3261)
                                                  at android.os.Binder.execTransact(Binder.java:580)

**Comment by Blankj** [comment]
actiityName是带包名的全路径吗

**Comment by stoneLee81** [comment]
是的，我换回1.5.0的类就正常了

**Comment by Blankj** [comment]
你看下两个源码的差别

**Comment by stoneLee81** [comment]
Utils.getContext().startActivity 最大的差别在这里

**Comment by Blankj** [comment]
我Demo怎么可以的呢，你的咋不行

**Comment by stoneLee81** [comment]
额，我还是那个类单独拷贝出来，单独用吧

**Comment by Blankj** [comment]
你帮找下bug么，看具体是哪出问题了哈

**Comment by stoneLee81** [comment]
我是直接在类里面调用的activity,然后穿了一个对象过去，最新版报错序列化出错

**Comment by Blankj** [comment]
我知道了，我参数写错了，最后一个动画应该为null的

**Comment by Blankj** [comment]
下版本修正会
