### ISSUE TITLE
下载下来后运行直接崩溃

### ISSUE THREAD

**Issue by Xanthuim** [Blankj/AndroidUtilCode#228]
环境：
Windows 7
AS 3.0-canary-8

错误信息：

`Process: com.blankj.androidutilcode, PID: 8293
                                                                          java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_773e439/Offline;
                                                                              at com.blankj.utilcode.util.Utils.$jacocoInit(Utils.java:0)
                                                                              at com.blankj.utilcode.util.Utils.init(Utils.java:0)
                                                                              at com.blankj.androidutilcode.UtilsApp.onCreate(UtilsApp.java:33)
                                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1031)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5277)
                                                                              at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                              at android.os.Looper.loop(Looper.java:227)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6102)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:961)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_773e439.Offline" on path: DexPathList[[zip file "/data/app/com.blankj.androidutilcode-1/base.apk", zip file "/data/app/com.blankj.androidutilcode-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.blankj.androidutilcode-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.blankj.androidutilcode-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.blankj.androidutilcode-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.blankj.androidutilcode-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.blankj.androidutilcode-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.blankj.androidutilcode-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.blankj.androidutilcode-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.blankj.androidutilcode-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.blankj.androidutilcode-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.blankj.androidutilcode-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.blankj.androidutilcode-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                              at com.blankj.utilcode.util.Utils.$jacocoInit(Utils.java:0) 
                                                                              at com.blankj.utilcode.util.Utils.init(Utils.java:0) 
                                                                              at com.blankj.androidutilcode.UtilsApp.onCreate(UtilsApp.java:33) 
                                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1031) 
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5277) 
                                                                              at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                              at android.os.Looper.loop(Looper.java:227) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6102) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:961) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822) 
                                                                          	Suppressed: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_773e439.Offline
                                                                              at java.lang.Class.classForName(Native Method)
                                                                              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                              at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                              		... 14 more
                                                                           Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Comment by Blankj** [comment]
拿稳定版的AS试试

**Comment by wrightakencom** [comment]
Not subject to change in thread  , 
does not read  #thefeed /start over 
with the help of products herein intended recipient of a change  !
