### ISSUE TITLE
ToastUtils.setBgColor方法在魅族Pro5崩溃报错

### ISSUE THREAD

**Issue by conghuahuadan** [Blankj/AndroidUtilCode#325]
ToastUtils.setBgColor方法在魅族Pro5崩溃报错，Flyme6.1，安卓5.1

`Process: com.blankj.androidutilcode, PID: 14775
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(android.graphics.ColorFilter)' on a null object reference
                                                                                at com.blankj.utilcode.util.ToastUtils.setBgAndGravity(ToastUtils.java:242)
                                                                                at com.blankj.utilcode.util.ToastUtils.access$200(ToastUtils.java:31)
                                                                                at com.blankj.utilcode.util.ToastUtils$1.run(ToastUtils.java:216)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5574)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Comment by Blankj** [comment]
Toast 所持有的 View 的背景获取到为空才报的异常，我现在改成判空的了

**Comment by Blankj** [comment]
试试 1.9.9 版本哈

**Comment by conghuahuadan** [comment]
![image](https://user-images.githubusercontent.com/20864280/33430756-a5134b4e-d60c-11e7-9f14-f9072d34c34d.png)

没有崩溃，不过背景颜色有问题

**Comment by conghuahuadan** [comment]
通过showShort和showLong方法，在真机和原生Toast的样式有出入

能改写成这种模式吗：

        if (toast == null) {
            toast = Toast.makeText(context, resId, Toast.LENGTH_SHORT);
        }
        toast.setText(resId);
        toast.show();

**Comment by Blankj** [comment]
你这魅族 Toast 修改过的吧，把 Toast 内部的 TextView 颜色为咖啡色，你点击 Short 和 Long 显示出来的是咖啡色的吧。

**Comment by Blankj** [comment]
你试试 1.9.10 版本吧

**Comment by conghuahuadan** [comment]
可以
