### ISSUE TITLE
多次切换点击ActivityUtils Demo 中列表导致崩溃，比如切换了CLz、Clz Opt,再切换到Clz Opt就会崩

### ISSUE THREAD

**Issue by hymbo** [Blankj/AndroidUtilCode#380]
java.lang.NullPointerException: Argument 'options' of type Bundle (#2 out of 3, zero-based) is marked by @android.support.annotation.NonNull but got null for it
                                                                              at com.blankj.utilcode.util.ActivityUtils.startActivity(ActivityUtils.java:110)
                                                                              at com.blankj.androidutilcode.feature.core.activity.ActivityActivity.onWidgetClick(ActivityActivity.java:138)
                                                                              at com.blankj.androidutilcode.base.BaseActivity.onClick(BaseActivity.java:63)

**Comment by Blankj** [comment]
安卓版本问题，已修复现在
