### ISSUE TITLE
请教一个问题？

### ISSUE THREAD

**Issue by ylmyg** [Blankj/AndroidUtilCode#421]
我用了作者的缓存工具类，但是启用缓存的时候报错
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
                                                       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
                                                       at android.os.Handler.handleCallback(Handler.java:743)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:150)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5659)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
                                                    Caused by: java.lang.NullPointerException: u should init first
                                                       at com.blankj.utilcode.util.Utils.getApp(Utils.java:122)
                                                       at com.blankj.utilcode.util.CacheUtils.getInstance(CacheUtils.java:107)
                                                       at com.blankj.utilcode.util.CacheUtils.getInstance(CacheUtils.java:68)
                                                       at yang.nesnd.fragment.zhihu.today.TodayPresenter$1.onNext(TodayPresenter.java:47)
                                                       at yang.nesnd.fragment.zhihu.today.TodayPresenter$1.onNext(TodayPresenter.java:38)
                                                       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
                                                       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
是不是缓存要先要初始化？不是很明白这个错误是什么意思？

**Comment by houyanbing** [comment]
Caused by: java.lang.NullPointerException: u should init first。
要先初始化

**Comment by qzqs** [comment]
但是我没有找到初始化的方法，奇怪了

**Comment by houyanbing** [comment]
Utils.init();  写在自己定义的application onCreate方法里
