### ISSUE TITLE
LogUtil奔溃

### ISSUE THREAD

**Issue by kylin0628** [Blankj/AndroidUtilCode#444]
如标题报异常java.lang.ExceptionInInitializerError

**Comment by Blankj** [comment]
日志栈，可否复现？

**Comment by BladeCode** [comment]
升级到最新的版本 1.13.7
``` java
04-08 03:16:57.668 6628-6628/com.xxx.yyy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.yyy, PID: 6628
    java.lang.ExceptionInInitializerError
        at com.blankj.utilcode.util.LogUtils.i(LogUtils.java:131)
        at com.xxx.yyy.manager.PermissionsManager$1$3.onSuccess(PermissionsManager.java:188)
        at io.realm.Realm$1$1.run(Realm.java:1502)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
     Caused by: java.lang.NullPointerException: u should init first
        at com.blankj.utilcode.util.Utils.getApp(Utils.java:109)
        at com.blankj.utilcode.util.LogUtils$Config.<init>(LogUtils.java:585)
        at com.blankj.utilcode.util.LogUtils$Config.<init>(LogUtils.java:581)
        at com.blankj.utilcode.util.LogUtils.<clinit>(LogUtils.java:87)
        at com.blankj.utilcode.util.LogUtils.i(LogUtils.java:131) 
        at com.xxx.yyy.manager.PermissionsManager$1$3.onSuccess(PermissionsManager.java:188) 
        at io.realm.Realm$1$1.run(Realm.java:1502) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6823) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451) 
```
出错位置
```java
com.xxx.yyy.manager.PermissionsManager$1$3.onSuccess(PermissionsManager.java:188)
```
原因是我这里调用了你库提供的打印日志的方法。
`LogUtils.i("xxxxxx")`
我不知道是哪里出错了，已经在MyApplication 的onCreate()方法中初始化了
```java
    private static MyApplication instance;

    public static MyApplication getInstance() {
        return instance;
    }
    ......
    @Override
    public void onCreate() {
        super.onCreate();
        Utils.init(instance);
        initLeakCanary();
//        initLog();
    }
```

**Comment by BladeCode** [comment]
@kylin0628 看看Application中初始化`Utils.init(instance);`  导入的包是不是这个库。
我也出现同样的错误，原因是我不小心导入了`com.wdullaer.materialdatetimepicker`这个库的Utils
