### ISSUE TITLE
java.lang.NoClassDefFoundError: com.blankj.utilcode.util.Utils$1

### ISSUE THREAD

**Issue by edcedc** [Blankj/AndroidUtilCode#486]
05-08 16:53:02.516 10246-10246/? E/memtrack: Couldn't load memtrack module (No such file or directory)
05-08 16:53:02.516 10246-10246/? E/android.os.Debug: failed to load memtrack module: -2
05-08 16:53:03.326 10264-10264/? E/memtrack: Couldn't load memtrack module (No such file or directory)
05-08 16:53:03.326 10264-10264/? E/android.os.Debug: failed to load memtrack module: -2
05-08 16:53:03.486 10287-10287/? E/dalvikvm: Could not find class 'com.blankj.utilcode.util.Utils$1', referenced from method com.blankj.utilcode.util.Utils.<clinit>
05-08 16:53:03.486 10287-10287/? E/dalvikvm: Could not find class 'com.blankj.utilcode.util.PermissionUtils$PermissionActivity', referenced from method com.blankj.utilcode.util.Utils.setTopActivityWeakRef
05-08 16:53:03.486 10287-10287/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.edc.dmt, PID: 10287
                                                   java.lang.NoClassDefFoundError: com.blankj.utilcode.util.Utils$1
                                                       at com.blankj.utilcode.util.Utils.<clinit>(Utils.java:42)
                                                       at com.edc.dmt.mar.MyApplication.onCreate(MyApplication.java:28)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:736)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by edcedc** [comment]
目前 compile 'com.blankj:utilcode:1.12.6'
为什么会初始化失败??

**Comment by Blankj** [comment]
不知道你这操作，试试最新版本吧。

**Comment by edcedc** [comment]
我是要在4.4.4机器运行的
试了最新包会出现Unable to get provider android.support.v4.content.FileProvider4Util异常
MultiDex未分包
解决方案：https://blog.csdn.net/juesai2015/article/details/78789244
就是不知道为什么会出现异常，是因为用了高版本API吗

**Comment by Blankj** [comment]
dex 大小超限了，所以要分多个 dex 了。

**Comment by edcedc** [comment]
多谢指点
