### ISSUE TITLE
ToastUtil Android 7.1 上偶尔出现崩溃错误

### ISSUE THREAD

**Issue by spd-heshuip** [Blankj/AndroidUtilCode#487]
在一个非Activity类中使用ToastUtil.showShort()出现了一下崩溃；
Fatal Exception: android.view.WindowManager$BadTokenException: 
Unable to add window -- token android.os.BinderProxy@1c4411f is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
       at android.widget.Toast$TN.handleShow(Toast.java:459)
       at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6236)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by Blankj** [comment]
版本号是什么？

**Comment by spd-heshuip** [comment]
com.blankj:utilcode:1.13.3

**Comment by Blankj** [comment]
用最新版本哈，你那个版本获取 topActivityOrApp 有点问题哈，没有判断前后台

**Comment by Jiiiiiin** [comment]
@Blankj 使用该类的时候遇到另外一个问题，应该同样是topActivityOrApp导致的：

```gralde
# 项目使用插件版本：
api 'com.blankj:utilcode:1.12.3'
```

常规使用，在线手机到的崩溃信息如下：
![](https://ws3.sinaimg.cn/large/006tKfTcgy1fr618cxb6qj31kw12lgq5.jpg)

@Blankj 能否解决一下？因为应用中所有toast我们都是用你的插件打出来的，不想去改了。谢谢

**Comment by Blankj** [comment]
你这不是吧，1.12.3 版本的 toast 没用 topActivityOrApp，你这报的异常也不像是我的原因啊，你看看报错的那个类 getPackageName 相关的代码 有个空指针

**Comment by Jiiiiiin** [comment]
@Blankj 嗯 之前的版本是api 'com.blankj:utilcode:1.12.3' 不是api 'com.blankj:utilcode:1.15.0'
