### ISSUE TITLE
想请问下其中的权限管理方案兼容了国产ROM吗

### ISSUE THREAD

**Issue by cervy** [Blankj/AndroidUtilCode#524]
**Describe the bug**

**The version of utilcode: [e.g. 1.16.3]**

**The device: [e.g. Nexus 5X]**

**The version of device: [e.g. API 27]**

**The code:**
[e.g.
```java
CrashUtils.init();
```
]

**The stack of crash:**
[e.g.
```
Caused by: java.lang.NullPointerException: u should init first
   at com.blankj.utilcode.util.Utils.getApp(Utils.java:98)
   at com.blankj.utilcode.util.CrashUtils.<clinit>(CrashUtils.java:55)
   at com.blankj.utilcode.util.CrashUtils.init(CrashUtils.java:168) 
   at com.blankj.androidutilcode.UtilsApp.initCrash(UtilsApp.java:71) 
   at com.blankj.androidutilcode.UtilsApp.onCreate(UtilsApp.java:33) 
```
]

**Screenshots**

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
试一下不就知道了么，其他库能做的我这也少不了，其他库做不到的，我这也许也能做到。可以参考这篇文章 https://juejin.im/post/5a55867af265da3e303c5fb3
