### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by pdog18** [Blankj/AndroidUtilCode#571]
```  ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     │ main, com.blankj.androidutilcode.UtilsApp$1.onCrash(UtilsApp.java:74)
     ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
     │ ************* Log Head ****************
     │ Time Of Crash      : 08-03 12-58-12
     │ Device Manufacturer: Xiaomi
     │ Device Model       : MI 6
     │ Android Version    : 8.0.0
     │ Android SDK        : 26
     │ App VersionName    : 1.18.0
     │ App VersionCode    : 1018000
     │ ************* Log Head ****************
     │ 
     │ java.lang.IllegalStateException: Only fullscreen activities can request orientation
     │ 	at android.os.Parcel.readException(Parcel.java:1951)
     │ 	at android.os.Parcel.readException(Parcel.java:1889)
     │ 	at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5775)
     │ 	at android.app.Activity.setRequestedOrientation(Activity.java:5803)
     │ 	at com.blankj.utilcode.util.ScreenUtils.setLandscape(ScreenUtils.java:147)
     │ 	at com.blankj.androidutilcode.feature.core.screen.ScreenActivity.onWidgetClick(ScreenActivity.java:70)
     │ 	at com.blankj.androidutilcode.base.BaseActivity.onClick(BaseActivity.java:63)
     │ 	at android.view.View.performClick(View.java:6266)
     │ 	at android.view.View$PerformClick.run(View.java:24730)
     │ 	at android.os.Handler.handleCallback(Handler.java:789)
     │ 	at android.os.Handler.dispatchMessage(Handler.java:98)
     │ 	at android.os.Looper.loop(Looper.java:171)
     │ 	at android.app.ActivityThread.main(ActivityThread.java:6688)
     │ 	at java.lang.reflect.Method.invoke(Native Method)
     │ 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
     │ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by Blankj** [comment]
<item name="android:windowIsTranslucent">true</item> 改为 false
8.0  bug

**Comment by Blankj** [comment]
下最新的试试 对 8.0 做了处理 https://github.com/Blankj/AndroidUtilCode/releases/download/1.18.1/util_1_18_1.apk
