### ISSUE TITLE
Screenshot is produce a NullPointerException

### ISSUE THREAD

**Issue by alihabbash** [Blankj/AndroidUtilCode#574]
Hi, in a button I call this when clicked
`ScreenUtils.screenShot(this);`

but I get a nullPointerException

The version I'm using is 1.18.2

I'm using Samsung Grand Prime Plus (J2 Prime).

Android OS Version is 6.0.1

The stack of crash:
```
08-06 21:43:39.273 11832-11832/com.ramiissa.dubaiing E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.ramiissa.dubaiing, PID: 11832
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ramiissa.dubaiing/com.ramiissa.dubaiing.ui.activities.main.MainActivity1}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7406)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:791)
                                                                           at com.blankj.utilcode.util.ScreenUtils.screenShot(Unknown Source)
                                                                           at com.blankj.utilcode.util.ScreenUtils.screenShot(Unknown Source)
                                                                           at com.ramiissa.dubaiing.ui.activities.main.MainActivity1.onCreate(MainActivity1.java:48)
                                                                           at android.app.Activity.performCreate(Activity.java:6904)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7406) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```
]

**Comment by Blankj** [comment]
I check the source code and add the code of `decorView.setWillNotCacheDrawing(false);`.  
I have publish the verison of 1.18.3 for fix it.

**Comment by alihabbash** [comment]
Thank you so much.
I have three questions please:
1- What permissions I need to provide in manifest file?
2- Do I need to request runtime  permissions or it done internally?
3- If I need permission, what do I need?

**Comment by Blankj** [comment]
You can check it in the site of https://developer.android.com/guide/topics/permissions/overview.
It can help u solve ru questions.
