### ISSUE TITLE
加固签名后使用getTopActivity获取的mActivityList为null

### ISSUE THREAD

**Issue by 775311653** [Blankj/AndroidUtilCode#604]
08-23 10:12:49.881 13717-13717/? W/System.err: java.lang.NoSuchFieldException: mActivityList
08-23 10:12:49.883 13717-13717/? W/System.err:     at java.lang.Class.getDeclaredField(Class.java:913)
        at com.blankj.utilcode.util.Utils$ActivityLifecycleImpl.getTopActivity(Unknown Source)
        at com.blankj.utilcode.util.ActivityUtils.getTopActivity(Unknown Source)
        at com.csii.ui.im.x.a(QuesIndexToDrawableUtil.java:84)

混淆签名后都能用，加固后再签名就报错了

**Comment by 775311653** [comment]
找到出问题的地方了，我把Utils.init(app);放到了一个intentService里面初始化，虽然这个service是放到app里面初始化的，但是不知为什么，加固签名后就无法使用mActivityList了。把Utils.init再次放回到app里面执行就没问题了
