### ISSUE TITLE
UriUtils.uri2File, NullPointerException

### ISSUE THREAD

**Issue by cymok** [Blankj/AndroidUtilCode#615]
**Describe the bug**
调用系统下载器下载完成后, 在广播接收器中执行以下java代码

**The version of utilcode: 1.19.4**

**The code:**
```java
	Uri downloadFileUri = dManager.getUriForDownloadedFile(myDownloadID);
	File file = UriUtils.uri2File(downloadFileUri, MediaStore.Files.FileColumns.DATA);//"_data"//MediaStore.Images.Media.DATA//第二个参数是否传错了
	AppUtils.installApp(file);
```

**The stack of crash:**
```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)' on a null object reference
	at com.blankj.utilcode.util.UriUtils.uri2File(UriUtils.java:56)
	at xxx.UpdateBroadcastReceiver.onReceive(UpdateBroadcastReceiver.java:44)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2778)
	... 9 more
```

**Comment by cymok** [comment]
![file0](https://user-images.githubusercontent.com/27819746/44895264-2c655100-ad26-11e8-8cdb-85f0bf1cddc7.png)
![file1](https://user-images.githubusercontent.com/27819746/44895265-2cfde780-ad26-11e8-8839-6dfb68450588.png)

**Comment by Blankj** [comment]
直接 `uri.getPath();` 就行

**Comment by Blankj** [comment]
你这原因可能是下载完后没有插入到媒体数据库里所以扫描不到吧
