### ISSUE TITLE
HASH算法名字错误，中间缺少-

### ISSUE THREAD

**Issue by li-xiaojun** [Blankj/AndroidUtilCode#619]
**Describe the bug**
HASH算法名字错误，中间缺少-，比如sha245加密报异常说找不到该消息摘要，改成sha-256后，没有问题了

**The version of utilcode:1.19.4**

**The device: 小米5**

**The version of device: API 27**

**The code:**
[e.g.
```kotlin
fun String.sha256Hmac(key: String) = EncryptUtils.encryptHmacSHA256ToString(this, key)
fun main(args: Array<String>) {
    println("123456".md5())
    println("123456".sha1())
    println("123456".sha256())
    println("123456".sha512())
}
```
]

**The stack of crash:**
[e.g.
```
java.security.NoSuchAlgorithmException: SHA256 MessageDigest not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.MessageDigest.getInstance(MessageDigest.java:167)
	at com.blankj.utilcode.util.EncryptUtils.hashTemplate(EncryptUtils.java:369)
	at com.blankj.utilcode.util.EncryptUtils.encryptSHA256(EncryptUtils.java:294)
	at com.blankj.utilcode.util.EncryptUtils.encryptSHA256ToString(EncryptUtils.java:284)
	at com.blankj.utilcode.util.EncryptUtils.encryptSHA256ToString(EncryptUtils.java:274)
```
]

**Comment by Blankj** [comment]
我这边都可以的，你的 targetSdk 是多少？

**Comment by Blankj** [comment]
最新版本已更新啦，你可以试下哈
