### ISSUE TITLE
 Unable to get provider com.blankj.utilcode.util.Utils$FileProvider4UtilCode

### ISSUE THREAD

**Issue by CuiErNaoAndLiuShanShan** [Blankj/AndroidUtilCode#631]
` java.lang.RuntimeException: Unable to get provider com.blankj.utilcode.util.Utils$FileProvider4UtilCode: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.Utils$FileProvider4UtilCode" on path: DexPathList[[zip file "/data/app/com.njsoft.retrofittest-1/base.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.njsoft.retrofittest-1/lib/x86, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5856)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.Utils$FileProvider4UtilCode" on path: DexPathList[[zip file "/data/app/com.njsoft.retrofittest-1/base.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.njsoft.retrofittest-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.njsoft.retrofittest-1/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5841)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
`

**Comment by Blankj** [comment]
开混淆了吗？

**Comment by CuiErNaoAndLiuShanShan** [comment]
啥格式在。。。大哥！

**Comment by Blankj** [comment]
![image](https://user-images.githubusercontent.com/17978187/45281203-ac9b6b80-b509-11e8-932f-ed1556db0bd3.png)
版本号什么的

**Comment by CuiErNaoAndLiuShanShan** [comment]
utilcode: 1.20.1

The device:Nexus 5 API 25
The version of device: API 28

**Comment by Blankj** [comment]
开混淆了吗项目

**Comment by CuiErNaoAndLiuShanShan** [comment]
没有开，打包都没有，直接debug版本的

**Comment by Blankj** [comment]
项目是插件化吗？

**Comment by CuiErNaoAndLiuShanShan** [comment]
只是一个简单的MVP，啥都没有

**Comment by Blankj** [comment]
你新建工程也会报这个错吗

**Comment by CuiErNaoAndLiuShanShan** [comment]
没有报这个错。。。

**Comment by Blankj** [comment]
那你找找原因是因为加了什么导致的

**Comment by CuiErNaoAndLiuShanShan** [comment]
我再排查下看看。。。。

**Comment by Blankj** [comment]
参考下面试试
```
allprojects {
    repositories {
        google()
        jcenter()
    }

    configurations.all {
        resolutionStrategy.eachDependency {
            if (it.requested.group == 'com.blankj'
                    && !it.requested.name.contains('utilcode')) {
                it.useVersion '1.20.1'
            }
        }
    }
}
```

**Comment by Blankj** [comment]
所以你是解决了吗？

**Comment by CuiErNaoAndLiuShanShan** [comment]
我把另外的Bug解决了，他莫名的不报刚才的错了，好尴尬啊

**Comment by Blankj** [comment]
ok 那有问题再说

**Comment by CuiErNaoAndLiuShanShan** [comment]
OK！麻烦了啊
