### ISSUE TITLE
不能适配4.4系统

### ISSUE THREAD

**Issue by mingxin-yang** [Blankj/AndroidUtilCode#637]
## Describe the bug

- The version of utilcode: 1.20.3
- The device: OPPO 6607
- The version of device: API 19

## The code of bug

```
put your code here
```

## The stack of crash
```
java.lang.RuntimeException: Unable to get provider com.blankj.utilcode.util.Utils$FileProvider4UtilCode: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.Utils$FileProvider4UtilCode" on path: DexPathList[[zip file "/data/app/im.autobot.mirrorlink-2.apk"],nativeLibraryDirectories=[/data/app-lib/im.autobot.mirrorlink-2, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5168)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4739)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4672)
        at android.app.ActivityThread.access$1500(ActivityThread.java:172)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1453)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5468)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.Utils$FileProvider4UtilCode" on path: DexPathList[[zip file "/data/app/im.autobot.mirrorlink-2.apk"],nativeLibraryDirectories=[/data/app-lib/im.autobot.mirrorlink-2, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4739) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4672) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:172) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1453) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:5468) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676) 
        at dalvik.system.NativeStart.main(Native Method) 
```
```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by mingxin-yang** [comment]
打开应用直接闪退

**Comment by Blankj** [comment]
? 怎么解决了

**Comment by mingxin-yang** [comment]
https://blog.csdn.net/DeMonliuhui/article/details/80392857用的这个方法，不是你代码的问题

**Comment by nxnyk** [comment]
> [https://blog.csdn.net/DeMonliuhui/article/details/80392857用的这个方法，不是你代码的问题](https://blog.csdn.net/DeMonliuhui/article/details/80392857%E7%94%A8%E7%9A%84%E8%BF%99%E4%B8%AA%E6%96%B9%E6%B3%95%EF%BC%8C%E4%B8%8D%E6%98%AF%E4%BD%A0%E4%BB%A3%E7%A0%81%E7%9A%84%E9%97%AE%E9%A2%98)

页面找不到了。。咋解决的兄弟

**Comment by Insane-neal** [comment]
In MainApplication, add this:
```java
@Override protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
```
