### ISSUE TITLE
ReflectUtils 反射失败，是我的用法不对么？

### ISSUE THREAD

**Issue by lks6123** [Blankj/AndroidUtilCode#677]
## 反射Service中的 startForeground 方法。 这个方法在自己实现的LinphoneService中有重写

- The version of utilcode: 1.21.0
- The device: 小米6
- The version of device: API 26

## The code of bug

```
1. ReflectUtils.reflect("com.ucloudlink.simbox.linphone.LinphoneService").method("startForeground", NOTIF_ID, notification).get();
2. ReflectUtils.reflect(this.getClass()).method("startForeground", NOTIF_ID, notification).get();

```

## The stack of crash
```
 Caused by: com.ucloudlink.simbox.util.ReflectUtils$ReflectException: java.lang.IllegalArgumentException: Expected receiver of type android.app.Service, but got java.lang.Class<com.ucloudlink.simbox.linphone.LinphoneService>
        at com.ucloudlink.simbox.util.ReflectUtils.method(ReflectUtils.java:313)
        at com.ucloudlink.simbox.util.ReflectUtils.method(ReflectUtils.java:296)
        at com.ucloudlink.simbox.linphone.LinphoneService.startForeground(LinphoneService.java:356)
        at com.ucloudlink.simbox.linphone.LinphoneService.onCreate(LinphoneService.java:291)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3443)
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
你能重写 startForeground ？它是 final 的啊，这是你调用不对的问题吧。 人家这个函数是 public 的你反射什么？
