### ISSUE TITLE
金立手机上闪退

### ISSUE THREAD

**Issue by blusewang** [Blankj/AndroidUtilCode#683]
## Describe the bug

- The version of utilcode: 1.17.1
- The device: GIONEE GN9012
- The version of device: 23

## The code of bug

```kotlin
CacheDiskUtils.getInstance().getJSONObject("apps", JSONObject())
```

## The stack of crash

```
java.lang.IllegalStateException: CacheDiskUtils.getInstan…ect("apps", JSONObject()) must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2552)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
Caused by: java.lang.IllegalStateException: CacheDiskUtils.getInstan…ect("apps", JSONObject()) must not be null
        at com.yxggwzx.cashier.a.b.b(AppHelper.kt:20)
        at com.yxggwzx.cashier.application.CApp$b.onActivityStarted(CApp.kt:75)
        at android.app.Application.dispatchActivityStarted(Application.java:205)
        at android.app.Activity.onStart(Activity.java:1164)
        at android.support.v4.app.i.onStart(FragmentActivity.java:614)
        at android.support.v7.app.d.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1245)
        at android.app.Activity.performStart(Activity.java:6311)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2515)
        ... 9 more
java.lang.IllegalStateException: CacheDiskUtils.getInstan…ect("apps", JSONObject()) must not be null
        at com.yxggwzx.cashier.a.b.b(AppHelper.kt:20)
        at com.yxggwzx.cashier.application.CApp$b.onActivityStarted(CApp.kt:75)
        at android.app.Application.dispatchActivityStarted(Application.java:205)
        at android.app.Activity.onStart(Activity.java:1164)
        at android.support.v4.app.i.onStart(FragmentActivity.java:614)
        at android.support.v7.app.d.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1245)
        at android.app.Activity.performStart(Activity.java:6311)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2515)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
kotlin 的吗？

**Comment by blusewang** [comment]
> kotlin 的吗？

嗯啊

**Comment by Blankj** [comment]
偶现还是必现？只有金立这样吗？

**Comment by blusewang** [comment]
> 偶现还是必现？只有金立这样吗？

这是我从崩溃收集中找到的。今天一天就这一个用户的手机十几次上报。
我当前能确定的是：今天我的这一个用户设备有这情况。
我一时没有足够的数据与条件断言，这是否波及GIONEE GN9012 这个机型的所有设备。
抱歉我这也没有这个机型的真机用来重现。

我还观察到这设备今天还报了些平常的layout 的xml文件里的Button解析不了。由此，我感觉问题也可能就在他的系统本身。

如果你凭我提供的信息也无法判断问题所在，那就当是这货系统本身有问题，略过。若今后还有同类发现，我再来反馈！

谢谢！
