### ISSUE TITLE
PermissionActivity 启动崩溃Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by a512509050** [Blankj/AndroidUtilCode#715]
## Describe the bug
PermissionUtils$PermissionActivity8.0启动崩溃
**Only fullscreen activities can request orientation**
在SplashActivity#onCreate方法中请求权限崩溃

- The version of utilcode: 1.21.2
- The device: 小米mix2
- The version of device: API26

## The stack of crash

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.digg.shike/com.blankj.utilcode.util.PermissionUtils$PermissionActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2852)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6672)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
你设置 setRequestedOrientation 了？

**Comment by Blankj** [comment]
那你过滤一下我这个 PermissionActivity

**Comment by a512509050** [comment]
好吧
