### ISSUE TITLE
不支持androidx

### ISSUE THREAD

**Issue by huangxunlei** [Blankj/AndroidUtilCode#727]
## Describe the bug

环境 :kotlin   androidx

## The code of bug

```
put your code here
```

## The stack of crash

```
ava.lang.RuntimeException: Unable to get provider com.blankj.utilcode.util.Utils$FileProvider4UtilCode: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.Utils$FileProvider4UtilCode" on path: DexPathList[[zip file "/data/app/***/base.apk"],nativeLibraryDirectories=[/data/app/***//lib/arm64, /data/app/***//base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6306)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5821)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5739)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```
-->

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by qrc0403** [comment]
同希望作者可以发布androidx版本

**Comment by cxyzy1** [comment]
同求androidx版本，当前androidx已发布了稳定版本1.0.2了。

**Comment by Blankj** [comment]
implementation 'com.blankj:utilcodex:1.23.7'
