### ISSUE TITLE
1.22.0ToastUtils 的BUG，好像只在MIUI上面有。

### ISSUE THREAD

**Issue by 231599447** [Blankj/AndroidUtilCode#731]
## Describe the bug

- The version of utilcode:  1.22.0 -->
- The device: 联想K3note miui9 -->
- The version of device: API 23 -->

## The code of bug

```
put your code here
```

## The stack of crash
    java.lang.NoSuchMethodError: No virtual method areNotificationsEnabled()Z in class Landroid/support/v4/app/NotificationManagerCompat; or its super classes (declaration of 'android.support.v4.app.NotificationManagerCompat' appears in /data/app/com.android.candy.lock-1/split_lib_dependencies_apk.apk)
        at com.blankj.utilcode.util.ToastUtils$ToastFactory.makeToast(ToastUtils.java:341)
        at com.blankj.utilcode.util.ToastUtils$1.run(ToastUtils.java:254)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

**Comment by 231599447** [comment]
找到问题的原因了。。
com.android.support:support-v4:25.4.0'
版本低于25的时候，没有此方法。。
