### ISSUE TITLE
PermissionActivity 當 DexGuard 混淆後會相同於 ActivityUtils.getTopActivity()

### ISSUE THREAD

**Issue by ktasl** [Blankj/AndroidUtilCode#733]
- The version of utilcode:  1.22.0
- The device:  全裝置
- The version of device: 全版本

## The stack of crash
```
E/WindowManager: android.view.WindowLeaked: Activity o.wI$a has leaked window DecorView@76a48c8[] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:505)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:330)
        at o.ut.show(**:464)
        at o.ut$b.ʽ(**:2189)
        at o.btc.ॱ(**:456)
        at o.brK.ˏ(**:60)
        at o.brK.ˋ(Unknown Source:4)
        at o.brL.ˏ(Unknown Source:0)
        at o.wI.ॱ(**:217)
        at o.wI.ˊ(**:38)
        at o.wI$a.onCreate(**:306)
        at android.app.Activity.performCreate(Activity.java:6986)
```
其中 o.wI$a = PermissionActivity.java

比照Code發現
```        private void setTopActivity(final Activity activity) {
            if (activity.getClass() == PermissionUtils.PermissionActivity.class) return;
            if (PERMISSION_ACTIVITY_CLASS_NAME.equals(activity.getClass().getName())) return;
            if (mActivityList.contains(activity)) {
                if (!mActivityList.getLast().equals(activity)) {
                    mActivityList.remove(activity);
```

因此這一段會繼續做下去導致 PermissionActivity = topActivity

**Comment by Blankj** [comment]
不能防混吗

**Comment by ktasl** [comment]
可以呀，只是當初沒想到會有 PermissionActivity 在 PermissionUtils 中
所以應該就是針對 PermissionUtils.PermissionActivity 整個不混淆吧

不曉得您那邊方便寫一個防混文件嗎？

**Comment by ktasl** [comment]
應該以 proguard為主就好，不過換我不熟，proguard不會將className 混淆嗎？
主要是可能寫在 readme.md裡面提醒大家就好，避免有混淆className的狀態下去針對getTopActivity做任何事情
感謝大大

**Comment by Blankj** [comment]
四大组件的子类类名不都不应该混淆的么，https://github.com/Blankj/FreeProGuard
```
# 保留我们使用的四大组件，自定义的 Application 等等这些类不被混淆
# 因为这些子类都有可能被外部调用
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Appliction
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class * extends android.view.View
-keep public class com.android.vending.licensing.ILicensingService
```
