### ISSUE TITLE
toast

### ISSUE THREAD

**Issue by zhaoxiuyu** [Blankj/AndroidUtilCode#747]
java.lang.Exception: denglibo Toast callstack! strTip=天气信息不存在
    at android.widget.Toast.show(Toast.java:127)
    at com.blankj.utilcode.util.ToastUtils$SystemToast.show(ToastUtils.java:385)
    at com.blankj.utilcode.util.ToastUtils$1.run(ToastUtils.java:266)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by Blankj** [comment]
1.22.2 修复了已经
