### ISSUE TITLE
关于APP安装的问题

### ISSUE THREAD

**Issue by wexia** [Blankj/AndroidUtilCode#751]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:605)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
        at com.blankj.utilcode.util.AppUtils.getInstallAppIntent(AppUtils.java:940)
        at com.blankj.utilcode.util.AppUtils.installApp(AppUtils.java:84)
        at com.blankj.utilcode.util.AppUtils.installApp(AppUtils.java:72)

版本：1.22.2

**Comment by Blankj** [comment]
不好意思，发版删了点东西，已发布 1.22.3。你试试吧
