### ISSUE TITLE
SPUtils 發生 java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by ktasl** [Blankj/AndroidUtilCode#770]
## Describe the bug

- The version of utilcode:  1.21.x
- The device: HTC_2Q4D100

## The code of bug

```java
Fatal Exception: java.util.ConcurrentModificationException
       at android.support.v4.util.SimpleArrayMap.put(Unknown Source:444)
       at com.blankj.utilcode.util.SPUtils.getInstance(Unknown Source:68)
       at com.blankj.utilcode.util.SPUtils.getInstance(Unknown Source:33)
       at com.ooxx.Application.onTrimMemory(Unknown Source:198)
       at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:5686)
```

**Comment by Blankj** [comment]
你版本太老啦，更新下 1.22.7
