### ISSUE TITLE
RSA加密文件格式不对

### ISSUE THREAD

**Issue by KevinNum67** [Blankj/AndroidUtilCode#784]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug
java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: invalid key format
	at sun.security.rsa.RSAKeyFactory.engineGeneratePublic(Unknown Source)
	at java.security.KeyFactory.generatePublic(Unknown Source)
	at com.rsa.test.RSATest.rsaTemplate(RSATest.java:108)
	at com.rsa.test.RSATest.encryptRSA(RSATest.java:62)
	at com.rsa.test.RSATest.main(RSATest.java:41)
Caused by: java.security.InvalidKeyException: invalid key format
	at sun.security.x509.X509Key.decode(Unknown Source)
	at sun.security.x509.X509Key.decode(Unknown Source)
	at sun.security.rsa.RSAPublicKeyImpl.<init>(Unknown Source)
	at sun.security.rsa.RSAKeyFactory.generatePublic(Unknown Source)
	... 5 more

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by KevinNum67** [comment]
用openssl生成的key文件的格式不对，导致这里读取不了

**Comment by Blankj** [comment]
我这边只关心数据和密钥，你要不把生成的数据和密钥发上来我看下对不对
