### ISSUE TITLE
部分机型V1.22.0版本ActivityUtils跳转异常发生Crash,之前V1.19.0是好的,在更新日志里并没有看到最近对ActivityUtils进行了修改,但是实际上是改了的

### ISSUE THREAD

**Issue by cvsong** [Blankj/AndroidUtilCode#803]
java.lang.IllegalArgumentException
2
    at android.os.Parcel.readException(Parcel.java:2017)
3
    at android.os.Parcel.readException(Parcel.java:1959)
4
    at android.app.IActivityManager$Stub$Proxy.isTopOfTask(IActivityManager.java:8653)
5
    at android.app.Activity.isTopOfTask(Activity.java:6428)
6
    at android.app.Activity.cancelInputsAndStartExitTransition(Activity.java:4656)
7
    at android.app.Activity.startActivityForResult(Activity.java:4633)
8
    at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
9
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
10
    at android.app.Activity.startActivity(Activity.java:4929)
11
    at com.blankj.utilcode.util.ActivityUtils.startActivity(ActivityUtils.java:1526)
12
    at com.blankj.utilcode.util.ActivityUtils.startActivity(ActivityUtils.java:601)
13
    at com.renying.matchu.ui.start.activity.LauncherActivity.y(LauncherActivity.java:292)
14
    at com.renying.matchu.ui.start.activity.LauncherActivity.b(LauncherActivity.java:49)
15
    at com.renying.matchu.ui.start.activity.LauncherActivity$4.run(LauncherActivity.java:242)
16
    at android.os.Handler.handleCallback(Handler.java:790)
17
    at android.os.Handler.dispatchMessage(Handler.java:99)
18
    at android.os.Looper.loop(Looper.java:192)
19
    at android.app.ActivityThread.main(ActivityThread.java:6800)
20
    at java.lang.reflect.Method.invoke(Native Method)
21
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
22
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)

**Comment by Blankj** [comment]
所以有了什么区别？

**Comment by cvsong** [comment]
这个方法出现了改变   
 private static boolean startActivity(final Intent intent,
                                         final Context context,
                                         final Bundle options) {
        if (!isIntentAvailable(intent)) {
            Log.e("ActivityUtils", "intent is unavailable");
            return false;
        }
        if (!(context instanceof Activity)) {
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        }
        if (options != null && Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
            context.startActivity(intent, options);
        } else {
            context.startActivity(intent);
        }
        return true;
    }

**Comment by Blankj** [comment]
你的 isIntentAvailable 返回 false 吗

**Comment by cvsong** [comment]
试了一下 返回FALSE  出异常的返回的也是false  日志显示是在ActivityUtils的1526行出现问题

**Comment by Blankj** [comment]
所以你的 intent 合法吗，可以找到存在的 Activity 吗

**Comment by cvsong** [comment]
是的  可能是我的转场动画时间过长 导致个别机型崩溃 或者是使用了handler进行延时跳转导致的

**Comment by Blankj** [comment]
isIntentAvailable 返回 false 是因为你的 intent 不合法，找不到对应的 Activity，不是你说的这个问题
