### ISSUE TITLE
魅族8.1 安装app显示解析包错误

### ISSUE THREAD

**Issue by oneapp1e** [Blankj/AndroidUtilCode#809]
## Describe the bug

- The version of utilcode: 1.23.0
- The device: 魅族 16X
- The version of device: 8.1

## The code of bug
01-21 20:31:23.645 13417-13431/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.blankj.utilcode.util.Utils$FileProvider4UtilCode uri content://.../download/apk20022.apk from pid=9395, uid=10032 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:707)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:530)
        at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:521)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:449)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:302)
        at android.os.Binder.execTransact(Binder.java:702)
01-21 20:31:23.646 9395-13416/? E/PkgInstaller: PackageInstaller: Permission denial when reading file content

因为没有请求权限 ，添加下面代码后正常
 context.grantUriPermission(packageName, data, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);

**Comment by Blankj** [comment]
`<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />`这个加了吗

**Comment by oneapp1e** [comment]
有这个权限

**Comment by Blankj** [comment]
你试试 1.23.1 吧，我加了
`Utils.getApp().grantUriPermission(Utils.getApp().getPackageName(), data, Intent.FLAG_GRANT_READ_URI_PERMISSION);`

**Comment by oneapp1e** [comment]
已经试过了，可以了
