### ISSUE TITLE
云测试报的错误

### ISSUE THREAD

**Issue by androidGhost** [Blankj/AndroidUtilCode#839]
![image](https://user-images.githubusercontent.com/9106628/53141502-5c9df600-35cb-11e9-9ba7-dd5dded8624d.png)

java.lang.NoSuchFieldException: mLastSrvView
	at java.lang.Class.getDeclaredField(Class.java:890)
	at com.blankj.utilcode.util.Utils$a.onActivityDestroyed(Utils.java:1346)
	at android.app.Application.dispatchActivityDestroyed(Application.java:245)
	at android.app.Activity.onDestroy(Activity.java:1668)
	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:346)
	at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)

使用版本 1.23.3

**Comment by Blankj** [comment]
这个只是输出了异常，不会引发崩溃的

**Comment by yuzhiqiang1993** [comment]
测试发现有概率会导致Activity直接退出，建议排查一下

**Comment by yuzhiqiang1993** [comment]
比如我从登录页面进入主页面，此时关闭登录页面，然后从主页面再跳转到登录页面，重新登录进入主页面时app就直接关掉了，没有成功跳转。老版本没有这个问题

**Comment by Blankj** [comment]
那你找相关 crash 堆栈，这个是我自己 try catch 住的只是输出了堆栈，不会引发 crash 的。

**Comment by androidGhost** [comment]
谢谢解答

**Comment by Blankj** [comment]
1.23.5 已发布
