### ISSUE TITLE
日志打印工具有个空指针异常(偶尔)

### ISSUE THREAD

**Issue by xiexin52k** [Blankj/AndroidUtilCode#859]
## Describe the bug

日志打印有一个偶尔出现的空指针异常

- The version of utilcode: 1.23.5
- The device: Android Tablet 
- The version of device: Android5.1.1

## The code of bug

```
LogUtils.i("");
```

## The stack of crash

```
 java.lang.NullPointerException: Attempt to get length of null array
        at com.blankj.utilcode.util.LogUtils.deleteDueLogs(LogUtils.java:527)
        at com.blankj.utilcode.util.LogUtils.createOrExistsFile(LogUtils.java:506)
        at com.blankj.utilcode.util.LogUtils.print2File(LogUtils.java:477)
        at com.blankj.utilcode.util.LogUtils.log(LogUtils.java:225)
        at com.blankj.utilcode.util.LogUtils.i(LogUtils.java:136)
```

**Comment by Blankj** [comment]
1.23.7 版本教你做人

**Comment by xiexin52k** [comment]
大柯基佬你今天要要穿女装. 不然怎么祝你节日快乐...

**Comment by Blankj** [comment]
我热爱工作，不穿女装
