### ISSUE TITLE
ShellUtils的execCmd 会造成死锁，阻塞线程

### ISSUE THREAD

**Issue by lisabiya** [Blankj/AndroidUtilCode#866]
## Describe the bug

ShellUtils的execCmd 会造成死锁，阻塞线程

## The code of bug          
         
```
120行     result = process.waitFor();
```

## 我的代码
当我在onCreateView中调用
```
NetworkUtils.isAvailableByPing()
```
偶尔会出现线程阻塞
```
Trace日志

at java.lang.Object.wait!(Native method)
  - waiting on <0x02dcccd9> (a java.lang.Object)
  at java.lang.ProcessManager$ProcessImpl.waitFor(ProcessManager.java:296)
  - locked <0x02dcccd9> (a java.lang.Object)
  at com.blankj.utilcode.util.ShellUtils.execCmd(ShellUtils.java:120)
  at com.blankj.utilcode.util.ShellUtils.execCmd(ShellUtils.java:33)
  at com.blankj.utilcode.util.NetworkUtils.isAvailableByPing(NetworkUtils.java:102)
  at com.blankj.utilcode.util.NetworkUtils.isAvailableByPing(NetworkUtils.java:87)
  at com.mdlib.droid.module.search.fragment.SearchFragment.initView(SearchFragment.java:203)
  at com.mdlib.droid.base.BaseFragment.onCreateView(BaseFragment.java:73)
```
当然主要是我自己的的问题，没有在子线程处理业务。提这个issue的主要原因是这个bug困扰了我一周，希望作者可以备注一下可能出现的这种问题。

**Comment by Blankj** [comment]
下版本会新增一个 isAvailableByPingAsync 方法

**Comment by daidaishuiping** [comment]
shellutils老是造成anr

**Comment by Blankj** [comment]
下版本会有 ShellUtils.execCmdAsync

**Comment by Blankj** [comment]
有很多方法本来就需要你们自己另起线程执行哈，不过 1.24.0 已加入 Async

**Comment by MaryDQ** [comment]
请问下ShellUtils能执行模拟手势操作命令吗？例如电脑上连接手机后，可以利用adb 指令控制手机
adb shell input keyevent 4   
像是这样模拟返回键
在android7.0手机版本以下

**Comment by Blankj** [comment]
你普通应用和电脑 adb 所使用的 shell 权限是不一致的。
