### ISSUE TITLE
OPPO手机，Android 8.1.0用了AndroidUtilCode库后编译安装进手机一打开秒闪退

### ISSUE THREAD

**Issue by xianfengting** [Blankj/AndroidUtilCode#885]
## Describe the bug

用了AndroidUtilCode库后编译安装进手机一打开秒闪退。

- The version of utilcode: 1.23.7
- The device: OPPO R11s
- The version of device: ColorOS版本：V5.2.1，Android版本：8.1.0

## The code of bug

```groovy
// 没有直接调用这个库API的代码，就是用了这个库以后应用秒闪退。
implementation 'com.blankj:utilcode:1.23.7'
```

## The stack of crash

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.src_resources.anti996.browser.android, PID: 18483
                  java.lang.RuntimeException: Unable to get provider com.blankj.utilcode.util.Utils$FileProvider4UtilCode: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.Utils$FileProvider4UtilCode" on path: DexPathList[[zip file "/data/app/com.src_resources.anti996.browser.android-5ohy5JsZUwS1QkASOi1ZPg==/base.apk"],nativeLibraryDirectories=[/data/app/com.src_resources.anti996.browser.android-5ohy5JsZUwS1QkASOi1ZPg==/lib/arm64, /system/lib64, /vendor/lib64]]
                      at android.app.ActivityThread.installProvider(ActivityThread.java:6717)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:6215)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6132)
                      at android.app.ActivityThread.-wrap1(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:197)
                      at android.app.ActivityThread.main(ActivityThread.java:7022)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.Utils$FileProvider4UtilCode" on path: DexPathList[[zip file "/data/app/com.src_resources.anti996.browser.android-5ohy5JsZUwS1QkASOi1ZPg==/base.apk"],nativeLibraryDirectories=[/data/app/com.src_resources.anti996.browser.android-5ohy5JsZUwS1QkASOi1ZPg==/lib/arm64, /system/lib64, /vendor/lib64]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at android.app.ActivityThread.installProvider(ActivityThread.java:6702)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:6215) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6132) 
                      at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839) 
                      at android.os.Handler.dispatchMessage(Handler.java:106) 
                      at android.os.Looper.loop(Looper.java:197) 
                      at android.app.ActivityThread.main(ActivityThread.java:7022) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837) 
```
## Screenshots
一开应用秒闪退，无法截屏。

**Comment by Blankj** [comment]
multidex 开启一下

**Comment by Ronrey100** [comment]
> multidex 开启一下

无效

**Comment by Blankj** [comment]
@Ronrey100 demo 呢 https://github.com/Blankj/AndroidUtilCode/releases

**Comment by Ronrey100** [comment]
用的demo：util_1_28_0_release.apk正常，但是我的依然报错。
`
   Process: com.sly.assistant, PID: 21602
    java.lang.RuntimeException: Unable to get provider com.blankj.utilcode.util.UtilsFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.UtilsFileProvider" on path: DexPathList[[zip file "/data/app/com.sly.assistant-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5424)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4992)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4927)
        at android.app.ActivityThread.access$1500(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:155)
        at android.app.ActivityThread.main(ActivityThread.java:5721)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.UtilsFileProvider" on path: DexPathList[[zip file "/data/app/com.sly.assistant-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5409)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4992) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4927) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:155) 
        at android.app.ActivityThread.main(ActivityThread.java:5721) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
    	Suppressed: java.lang.NoClassDefFoundError: com.blankj.utilcode.util.UtilsFileProvider
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:226)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
        at dalvik.system.DexPathList.findClass(DexPathList.java:321)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
        		... 14 more
    	Suppressed: java.lang.ClassNotFoundException: com.blankj.utilcode.util.UtilsFileProvider
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 13 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
`

**Comment by Ronrey100** [comment]
Rejecting re-init on previously-failed class java.lang.Class<com.blankj.utilcode.util.UtilsFileProvider>

**Comment by Blankj** [comment]
试试 https://developer.android.com/studio/build/multidex?hl=zh-cn#multidexkeepfile 的 
 multiDexKeepProguard

**Comment by Ronrey100** [comment]
> 试试 https://developer.android.com/studio/build/multidex?hl=zh-cn#multidexkeepfile 的
> multiDexKeepProguard

刚刚加了，还是不行

**Comment by Blankj** [comment]
> 刚刚加了，还是不行

那在你自己的 app 的 Manifest 文件里申明我这个 UtilsFileProvider 呢

**Comment by Ronrey100** [comment]
Clean了，申明了也还是不行，机器出厂是Android4.4，升级为了Android5.0.1
`
<provider
            tools:replace="android:authorities"
            android:authorities="my.ronrey"
            android:name="com.blankj.utilcode.util.UtilsFileProvider"></provider>
`

**Comment by Ronrey100** [comment]
> > 刚刚加了，还是不行
> 
> 行不行需要 clean 后再跑一遍试试，不 clean 可能没效果，实在不行再试试在你自己的 app 的 Manifest 文件里拷贝一份我这个 UtilsFileProvider 呢

Clean了，申明了也还是不行，机器出厂是Android4.4，升级为了Android5.0.1
`
<provider
            tools:replace="android:authorities"
            android:authorities="my.ronrey"
            android:name="com.blankj.utilcode.util.UtilsFileProvider"></provider>
`

**Comment by Blankj** [comment]
那我就不知道了

**Comment by Ronrey100** [comment]
> 那我就不知道了

请问下demo的源码在哪？我看看demo里面怎么来写的

**Comment by Blankj** [comment]
这个工程不就是源码么。。。

**Comment by Ronrey100** [comment]
> 这个工程不就是源码么。。。
对对，现在解决了，大概是因为，从Android Studio 3.0.2的版本，升级到了3.6.2的版本，support包也都更改成了androidx，
然后编译没问题，但是发布到5.1真机出问题了，出现错误java.lang.ClassNotFoundException: com.blankj.utilcode.util.UtilsFileProvider，
后来用升级后的AS版本创建一个简单新工程，引入utilcode编译及发布正常。对比了下旧工程和新工程的配置文件，发现有两点不同，新工程config增加了android.enableJetifier=true，移除了buildToolsVersion '28.0.2'，这个属性，我同样操作后，编译发布正常了，虽然还没有完全理解为什么not found class，但是好几年没搞Android，发现这个SDK变化及技术升级带来的变化太大了。

**Comment by Blankj** [comment]
用 androidx 需要使用 utilcodex 版本，移除 buildToolsVersion 其实还是在的，只是编译器会帮你自己选择版本，所以最终导致的问题还是没定位到吧

**Comment by Ronrey100** [comment]
> 用 androidx 需要使用 utilcodex 版本，移除 buildToolsVersion 其实还是在的，只是编译器会帮你自己选择版本，所以最终导致的问题还是没定位到吧

是的，后期回过头来再研究研究。但也有可能是我定义的buildToolsVersion版本问题，去掉后，编译器会根据TargetSdkVersion选择更合适的编译，所以就能够发布成功。
