### ISSUE TITLE
空指针异常，需要处理一下

### ISSUE THREAD

**Issue by folk113** [Blankj/AndroidUtilCode#928]
## Describe the bug

- The version of utilcode: 1.23.4 
- The device: honor 8
- The version of device:  API 27

## The code of bug

```
LogUtils.i("url:" + Config.MQTT_WEB_URL);
```

## The stack of crash

```
05-23 09:19:56.477  9044  9044 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
05-23 09:19:56.477  9044  9044 E AndroidRuntime: 	at com.blankj.utilcode.util.LogUtils.deleteDueLogs(LogUtils.java:530)
05-23 09:19:56.477  9044  9044 E AndroidRuntime: 	at com.blankj.utilcode.util.LogUtils.createOrExistsFile(LogUtils.java:509)
05-23 09:19:56.477  9044  9044 E AndroidRuntime: 	at com.blankj.utilcode.util.LogUtils.print2File(LogUtils.java:480)
05-23 09:19:56.477  9044  9044 E AndroidRuntime: 	at com.blankj.utilcode.util.LogUtils.log(LogUtils.java:227)
05-23 09:19:56.477  9044  9044 E AndroidRuntime: 	at com.blankj.utilcode.util.LogUtils.i(LogUtils.java:138)
05-23 09:19:56.477  9044  9044 E AndroidRuntime: 	at com.phubber.mqtt.model.MqttWebProxy.initHandler(MqttWebProxy.java:28)
05-23 09:19:56.477  9044  9044 E AndroidRuntime: 	at com.phubber.mqtt.model.MqttWebProxy.<init>(MqttWebProxy.java:22)
05-23 09:19:56.477  9044  9044 E AndroidRuntime: 	at com.phubber.mqtt.model.MqttWebProxy.getInstance(MqttWebProxy.java:16)
05-23 09:19:56.477  9044  9044 E AndroidRuntime: 	at com.phubber.mqtt.app.MqttApp.onCreate(MqttApp.java:34)
05-23 09:19:56.477  9044  9044 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
05-23 09:19:56.477  9044  9044 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
已知问题，下版本会修复

**Comment by Blankj** [comment]
1.24.0 已修复
