### ISSUE TITLE
在虚拟机上崩溃了

### ISSUE THREAD

**Issue by qinglok** [Blankj/AndroidUtilCode#948]
设备：Genymotion > Google Galaxy Nexus 
Android API 16
utilcodex:1.24.2

E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider com.blankj.utilcode.util.Utils$FileProvider4UtilCode: java.lang.SecurityException: Provider must not be exported
        at android.app.ActivityThread.installProvider(ActivityThread.java:4563)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)
        at android.app.ActivityThread.access$1300(ActivityThread.java:130)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.SecurityException: Provider must not be exported
        at androidx.core.content.FileProvider.attachInfo(FileProvider.java:386)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4560)

**Comment by Alexxiaopang** [comment]
我也是一样的问题

**Comment by Blankj** [comment]
试试拉最新的代码，我这边是没问题的
