### ISSUE TITLE
(BUG)[AndroidUtilCode version 1.25.0 ] When I click on the shutdown, the application crashes

### ISSUE THREAD

**Issue by XAMIR555** [Blankj/AndroidUtilCode#980]
#### Project Information
* Repository-----------:[Here](https://github.com/Blankj/AndroidUtilCode)
* Project Name---------: [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode/releases)
* Publisher------------: [Blankj](https://github.com/Blankj)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior
When I click on the  shutdown, the mobile  phone  should  be shutdown And the app should not crash.

#### Actual behavior
When I click on the shutdown, the application crashes

#### How to reproduce
* [Download ](https://github.com/Blankj/AndroidUtilCode/releases)and open the Application 
* click on Sub Util
* click on the Dengerous Demo
* Click the Shutdown option
* Note the Bug
* Browser/App version-:  version 1.25.0
* Operating system----: 9.0.0

#### Recording Of The Bug
![20190716_211716](https://user-images.githubusercontent.com/49812927/61313037-76c0b680-a7ae-11e9-91a3-fb7153c566e3.gif)

# Logcat

<pre><code>07-16 21:00:15.032 30874 30874 E AndroidRuntime: FATAL EXCEPTION: main
07-16 21:00:15.032 30874 30874 E AndroidRuntime: Process: com.blankj.androidutilcode, PID: 30874
07-16 21:00:15.032 30874 30874 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.ACTION_REQUEST_SHUTDOWN flg=0x10000000 (has extras) }
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2022)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:979)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:950)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at com.blankj.subutil.a.c.a(DangerousUtils.java:225)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at com.blankj.subutil.pkg.feature.dangerous.DangerousActivity.onDebouncingClick(DangerousActivity.kt:110)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at com.blankj.lib.base.BaseActivity$1.onClick(BaseActivity.java:27)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at com.blankj.utilcode.util.g$1.a(ClickUtils.java:152)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at com.blankj.utilcode.util.g$b.onClick(ClickUtils.java:212)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27787)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-16 21:00:15.032 30874 30874 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: FATAL EXCEPTION: main
07-16 21:00:26.340 31889 31889 E AndroidRuntime: Process: com.blankj.androidutilcode, PID: 31889
07-16 21:00:26.340 31889 31889 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.ACTION_REQUEST_SHUTDOWN flg=0x10000000 (has extras) }
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2022)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:979)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:950)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at com.blankj.subutil.a.c.a(DangerousUtils.java:225)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at com.blankj.subutil.pkg.feature.dangerous.DangerousActivity.onDebouncingClick(DangerousActivity.kt:110)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at com.blankj.lib.base.BaseActivity$1.onClick(BaseActivity.java:27)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at com.blankj.utilcode.util.g$1.a(ClickUtils.java:152)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at com.blankj.utilcode.util.g$b.onClick(ClickUtils.java:212)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27787)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-16 21:00:26.340 31889 31889 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: FATAL EXCEPTION: main
07-16 21:00:41.208 32092 32092 E AndroidRuntime: Process: com.blankj.androidutilcode, PID: 32092
07-16 21:00:41.208 32092 32092 E AndroidRuntime: java.lang.SecurityException: Permission Denial: not allowed to send broadcast android.intent.action.REBOOT from pid=32092, uid=10293
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1966)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1934)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1884)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.broadcastIntent(IActivityManager.java:3752)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1071)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:449)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at com.blankj.subutil.a.c.b(DangerousUtils.java:239)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at com.blankj.subutil.pkg.feature.dangerous.DangerousActivity.onDebouncingClick(DangerousActivity.kt:111)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at com.blankj.lib.base.BaseActivity$1.onClick(BaseActivity.java:27)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at com.blankj.utilcode.util.g$1.a(ClickUtils.java:152)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at com.blankj.utilcode.util.g$b.onClick(ClickUtils.java:212)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27787)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:25920)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:25736)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:26606)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact$broadcastIntent$(IActivityManager.java:10953)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:139)
07-16 21:00:41.208 32092 32092 E AndroidRuntime: 
</code></pre>

**Comment by Blankj** [comment]
Please see the method annotation.
