### ISSUE TITLE
(BUG)[AndroidUtilCode version 1.25.0 ] When I click on the Reboot, option the application crashes

### ISSUE THREAD

**Issue by XAMIR555** [Blankj/AndroidUtilCode#982]
#### Project Information
* Repository-----------:[Here](https://github.com/Blankj/AndroidUtilCode)
* Project Name---------: [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode/releases)
* Publisher------------: [Blankj](https://github.com/Blankj)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior

When I click on the  reboot option , the mobile  phone  should  be Reboot And the app should not crash.

#### Actual behavior

When I click on the Reboot, option the application crashes

#### How to reproduce
* [Download ](https://github.com/Blankj/AndroidUtilCode/releases)and open the Application 
* click on Sub Util
* click on the Dengerous Demo
* Click the Reboot option 
* Note the Bug
* Browser/App version-:  version 1.25.0
* Operating system----: 9.0.0

#### Recording Of The Bug
![20190717_112525](https://user-images.githubusercontent.com/49812927/61352444-37cc4880-a822-11e9-95a6-4b06428b596d.gif)

# Logcat

<pre><code>07-16 21:01:59.778 32385 32385 E AndroidRuntime: FATAL EXCEPTION: main
07-16 21:01:59.778 32385 32385 E AndroidRuntime: Process: com.blankj.androidutilcode, PID: 32385
07-16 21:01:59.778 32385 32385 E AndroidRuntime: java.lang.NullPointerException: crash test
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at com.blankj.utilcode.pkg.feature.CoreUtilActivity.onDebouncingClick(CoreUtilActivity.kt:123)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at com.blankj.lib.base.BaseActivity$1.onClick(BaseActivity.java:27)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at com.blankj.utilcode.util.g$1.a(ClickUtils.java:152)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at com.blankj.utilcode.util.g$b.onClick(ClickUtils.java:212)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27787)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-16 21:01:59.778 32385 32385 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-16 21:07:09.308  6149  6637 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-3
07-16 21:07:09.308  6149  6637 E AndroidRuntime: Process: jerryc05.unlockme, PID: 6149
07-16 21:07:09.308  6149  6637 E AndroidRuntime: java.lang.UnsupportedOperationException: java.lang.RuntimeException: takePicture failed
07-16 21:07:09.308  6149  6637 E AndroidRuntime: 	at jerryc05.unlockme.helpers.DeviceAdminHelper.showExceptionToNotification(Unknown Source:5)
07-16 21:07:09.308  6149  6637 E AndroidRuntime: 	at jerryc05.unlockme.helpers.camera.CameraBaseAPIClass.getImageFromDefaultCamera(:15)
07-16 21:07:09.308  6149  6637 E AndroidRuntime: 	at jerryc05.unlockme.services.ForegroundService$2.run(Unknown Source:23)
07-16 21:07:09.308  6149  6637 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-16 21:07:09.308  6149  6637 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-16 21:07:09.308  6149  6637 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-16 21:07:10.553  6823  6840 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
07-16 21:07:10.553  6823  6840 E AndroidRuntime: Process: jerryc05.unlockme, PID: 6823
07-16 21:07:10.553  6823  6840 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
07-16 21:07:10.553  6823  6840 E AndroidRuntime: 	at jerryc05.unlockme.services.ForegroundService$2.run(Unknown Source:2)
07-16 21:07:10.553  6823  6840 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-16 21:07:10.553  6823  6840 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-16 21:07:10.553  6823  6840 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: FATAL EXCEPTION: main
07-16 21:17:04.709 14308 14308 E AndroidRuntime: Process: com.blankj.androidutilcode, PID: 14308
07-16 21:17:04.709 14308 14308 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.ACTION_REQUEST_SHUTDOWN flg=0x10000000 (has extras) }
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2022)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:979)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:950)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at com.blankj.subutil.a.c.a(DangerousUtils.java:225)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at com.blankj.subutil.pkg.feature.dangerous.DangerousActivity.onDebouncingClick(DangerousActivity.kt:110)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at com.blankj.lib.base.BaseActivity$1.onClick(BaseActivity.java:27)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at com.blankj.utilcode.util.g$1.a(ClickUtils.java:152)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at com.blankj.utilcode.util.g$b.onClick(ClickUtils.java:212)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27787)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-16 21:17:04.709 14308 14308 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: FATAL EXCEPTION: main
07-16 21:17:19.999 14552 14552 E AndroidRuntime: Process: com.blankj.androidutilcode, PID: 14552
07-16 21:17:19.999 14552 14552 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.ACTION_REQUEST_SHUTDOWN flg=0x10000000 (has extras) }
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2022)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:979)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:950)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at com.blankj.subutil.a.c.a(DangerousUtils.java:225)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at com.blankj.subutil.pkg.feature.dangerous.DangerousActivity.onDebouncingClick(DangerousActivity.kt:110)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at com.blankj.lib.base.BaseActivity$1.onClick(BaseActivity.java:27)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at com.blankj.utilcode.util.g$1.a(ClickUtils.java:152)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at com.blankj.utilcode.util.g$b.onClick(ClickUtils.java:212)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27787)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-16 21:17:19.999 14552 14552 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: FATAL EXCEPTION: main
07-16 21:20:51.995 17367 17367 E AndroidRuntime: Process: com.blankj.androidutilcode, PID: 17367
07-16 21:20:51.995 17367 17367 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.ACTION_REQUEST_SHUTDOWN flg=0x10000000 (has extras) }
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2022)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:979)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:950)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at com.blankj.subutil.a.c.a(DangerousUtils.java:225)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at com.blankj.subutil.pkg.feature.dangerous.DangerousActivity.onDebouncingClick(DangerousActivity.kt:110)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at com.blankj.lib.base.BaseActivity$1.onClick(BaseActivity.java:27)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at com.blankj.utilcode.util.g$1.a(ClickUtils.java:152)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at com.blankj.utilcode.util.g$b.onClick(ClickUtils.java:212)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27787)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-16 21:20:51.995 17367 17367 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: FATAL EXCEPTION: main
07-16 21:21:09.990 17522 17522 E AndroidRuntime: Process: com.blankj.androidutilcode, PID: 17522
07-16 21:21:09.990 17522 17522 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.ACTION_REQUEST_SHUTDOWN flg=0x10000000 (has extras) }
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2022)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:979)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:950)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at com.blankj.subutil.a.c.a(DangerousUtils.java:225)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at com.blankj.subutil.pkg.feature.dangerous.DangerousActivity.onDebouncingClick(DangerousActivity.kt:110)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at com.blankj.lib.base.BaseActivity$1.onClick(BaseActivity.java:27)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at com.blankj.utilcode.util.g$1.a(ClickUtils.java:152)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at com.blankj.utilcode.util.g$b.onClick(ClickUtils.java:212)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27787)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-16 21:21:09.990 17522 17522 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: FATAL EXCEPTION: main
07-17 11:25:28.494 16544 16544 E AndroidRuntime: Process: com.blankj.androidutilcode, PID: 16544
07-17 11:25:28.494 16544 16544 E AndroidRuntime: java.lang.SecurityException: Permission Denial: not allowed to send broadcast android.intent.action.REBOOT from pid=16544, uid=10293
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1966)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1934)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1884)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.broadcastIntent(IActivityManager.java:3752)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1071)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:449)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at com.blankj.subutil.a.c.b(DangerousUtils.java:239)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at com.blankj.subutil.pkg.feature.dangerous.DangerousActivity.onDebouncingClick(DangerousActivity.kt:111)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at com.blankj.lib.base.BaseActivity$1.onClick(BaseActivity.java:27)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at com.blankj.utilcode.util.g$1.a(ClickUtils.java:152)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at com.blankj.utilcode.util.g$b.onClick(ClickUtils.java:212)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27787)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:25920)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:25736)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:26606)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact$broadcastIntent$(IActivityManager.java:10953)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:139)
07-17 11:25:28.494 16544 16544 E AndroidRuntime: 
</code></pre>

**Comment by Blankj** [comment]
Please see the method annotation.
