### ISSUE TITLE
Crash while use KeyboardUtils.hideSoftInput(Activity)

### ISSUE THREAD

**Issue by DCRain** [Blankj/AndroidUtilCode#991]
## Describe the bug

The specified child already has a parent. You must call removeView() on the child's parent

- The version of utilcode: 1.25.3
- The device: All
- The version of device: All

## The code of bug

```
KeyboardUtils.hideSoftInput(activity)
```

## The stack of crash

```java
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5038)
        at android.view.ViewGroup.addView(ViewGroup.java:4869)
        at android.view.ViewGroup.addView(ViewGroup.java:4826)
        at com.blankj.utilcode.util.KeyboardUtils.hideSoftInput(KeyboardUtils.java:95)
```
猜测原因：
```java
public static void hideSoftInput(@NonNull final Activity activity) {
        View view = activity.getCurrentFocus();
        if (view == null) {
            View focusView = activity.getWindow().getDecorView().findViewWithTag("keyboardTagView");
            if (focusView == null) {
                view = new EditText(activity);
                view.setTag("keyboardTagView");
            } else {
                view = focusView;//focusView!=null的时候，没先从parent中移除就直接addView导致的
            }
            ((ViewGroup) activity.getWindow().getDecorView()).addView(view, 0, 0);
            view.requestFocus();
        }
        hideSoftInput(view);
    }
```

**Comment by Blankj** [comment]
好的

**Comment by Blankj** [comment]
1.25.4 已可用

**Comment by DCRain** [comment]
辛苦
