### ISSUE TITLE
隐藏虚拟键盘闪退

### ISSUE THREAD

**Issue by yuhlzu** [Blankj/AndroidUtilCode#992]
## Describe the bug

- The version of utilcode: 1.25.0
- The device: mi6
- The version of device: 9

## The code of bug

```
 KeyboardUtils.hideSoftInput(ActivityLogin.this);
```

## The stack of crash

```
2019-07-31 01:32:00.044 30809-30809/com.lzu.yuh.lzu E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lzu.yuh.lzu, PID: 30809
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5038)
        at android.view.ViewGroup.addView(ViewGroup.java:4869)
        at android.view.ViewGroup.addView(ViewGroup.java:4826)
        at com.blankj.utilcode.util.KeyboardUtils.hideSoftInput(KeyboardUtils.java:98)
        at com.lzu.yuh.lzu.login.ActivityLogin$1.handleMessage(ActivityLogin.java:267)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6867)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

**Comment by Blankj** [comment]
升级到最新版本即可
